// React-JS/src/app/(admin)/(dashboards)/analytics/index.jsx
import PageBreadcrumb from '@/components/PageBreadcrumb';
import Analytics from './components/Analytics';
import AnalyticsReports from './components/AnalyticsReports';
import LocationBased from './components/LocationBased';
import PagesInteraction from './components/PagesInteraction';
import PerspectiveChart from './components/PerspectiveChart';
import ProductsStatistics from './components/ProductsStatistics';
import StatusOfMonthlyCampaign from './components/StatusOfMonthlyCampaign';
import SubscriptionDistribution from './components/SubscriptionDistribution';
import TrafficSource from './components/TrafficSource';
import UserChart from './components/UserChart';
import PageMeta from '@/components/PageMeta';
const Index = () => {
  return <>
      <PageMeta title="Analytics" />
      <main>
        <PageBreadcrumb title="Analytics" subtitle="Dashboard" />
        <div className="grid lg:grid-cols-3 grid-cols-1 gap-5 mb-5">
          <Analytics />
          <PerspectiveChart />
        </div>
        <div className="grid lg:grid-cols-12 grid-cols-1 gap-5 mb-5">
          <LocationBased />
          <PagesInteraction />
        </div>
        <UserChart />
        <ProductsStatistics />
        <div className="grid lg:grid-cols-4 grid-cols-1 gap-5">
          <AnalyticsReports />
          <StatusOfMonthlyCampaign />
          <SubscriptionDistribution />
          <TrafficSource />
        </div>
      </main>
    </>;
};
export default Index;

// Vuejs/src/views/dashboard/analytics/index.vue
<template>
  <Vertical>
    <PageTitle title="Analytics" subtitle="Dashboards" />
    <div class="grid lg:grid-cols-3 grid-cols-1 gap-5 mb-5">
      <Stat />
      <PlatformPerspective />
    </div>

    <div class="grid lg:grid-cols-12 grid-cols-1 gap-5 mb-5">
      <Location />
      <Interaction />
    </div>

    <div class="grid lg:grid-cols-3 grid-cols-1 gap-5 mb-5">
      <UserDevice />
      <SatisfactionLevel />
      <DailyVisit />
    </div>

    <div class="grid grid-cols-1 gap-5 mb-5">
      <ProductsStatistics />
    </div>

    <div class="grid lg:grid-cols-4 grid-cols-1 gap-5">
      <AnalyticsReports />
      <StatusofMonth />
      <Subscription />
      <Traffic />
    </div>
  </Vertical>
</template>

<script setup lang="ts">
import PageTitle from '@/components/PageTitle.vue'
import Vertical from '@/layouts/vertical.vue'
import Stat from './components/Stat.vue'
import PlatformPerspective from './components/PlatformPerspective.vue'
import Location from './components/Location.vue'
import Interaction from './components/Interaction.vue'
import UserDevice from './components/UserDevice.vue'
import SatisfactionLevel from './components/SatisfactionLevel.vue'
import DailyVisit from './components/DailyVisit.vue'
import ProductsStatistics from './components/ProductsStatistics.vue'
import AnalyticsReports from './components/AnalyticsReports.vue'
import StatusofMonth from './components/StatusofMonth.vue'
import Subscription from './components/Subscription.vue'
import Traffic from './components/Traffic.vue'

</script>
