// Nextjs-JS/src/app/(admin)/(dashboards)/hr/components/UpcomingScheduled.jsx
import React from 'react';
import Image from 'next/image';
import support from '@/assets/images/support.png';
const events = [{
  id: 1,
  day: '28',
  month: 'July',
  title: 'Meeting with Designer',
  time: '09:57 AM',
  createdBy: 'Admin'
}, {
  id: 2,
  day: '08',
  month: 'June',
  title: 'Developing Line Managers Conference',
  time: '10:54 AM',
  createdBy: 'HR'
}, {
  id: 3,
  day: '17',
  month: 'July',
  title: 'Airplane in Las Vegas',
  time: '12:00 PM',
  createdBy: 'HR'
}, {
  id: 4,
  day: '11',
  month: 'Nov',
  title: 'Hospitality Project Discuses',
  createdBy: 'Admin'
}, {
  id: 5,
  day: '20',
  month: 'Nov',
  title: 'Gartner Digital Workplace',
  time: '03:49 PM',
  createdBy: 'HR'
}, {
  id: 6,
  day: '04',
  month: 'Dec',
  title: 'Nordic People Analytics',
  time: '11:00 AM',
  createdBy: 'Admin'
}, {
  id: 7,
  day: '17',
  month: 'Jan',
  title: 'CIPD Festival of Work',
  time: '01:29 PM',
  createdBy: 'HR'
}, {
  id: 8,
  day: '03',
  month: 'Feb',
  title: 'HRO Today Forum',
  time: '02:15 PM',
  createdBy: 'Admin'
}, {
  id: 9,
  day: '15',
  month: 'Mar',
  title: 'HR Training Workshop',
  time: '09:00 AM',
  createdBy: 'HR'
}, {
  id: 10,
  day: '29',
  month: 'Apr',
  title: 'Marketing Strategy Review',
  time: '04:45 PM',
  createdBy: 'Marketing'
}, {
  id: 11,
  day: '10',
  month: 'May',
  title: 'Client Demo Presentation',
  time: '11:30 AM',
  createdBy: 'Admin'
}];
const UpcomingScheduled = () => {
  return <div className="card">
      <div className="card-header">
        <h6 className="card-title">Upcoming Scheduled</h6>
      </div>

      <div className="card-body">
        <div className="flex flex-col gap-4">
          {events.map(event => <div key={event.id} className="flex gap-3">
              <div className="flex flex-col items-center justify-center border rounded-sm size-12 border-default-200">
                <h6 className="text-default-800 font-semibold">{event.day}</h6>
                <span className="text-default-500">{event.month}</span>
              </div>

              <div>
                <h6 className="mb-1 text-default-900 text-sm font-medium">
                  {event.title}{' '}
                  {event.time && <small className="px-2 font-medium rounded text-xs py-0.5 bg-default-100 text-default-500">
                      {event.time}
                    </small>}
                </h6>
                <p className="text-default-500">Created by {event.createdBy}</p>
              </div>
            </div>)}
        </div>

        <div className="flex gap-3 p-2 mt-4 rounded-md bg-primary">
          <Image src={support} alt="Support" className="h-24 w-auto" />
          <div>
            <h6 className="mb-1 text-base text-white">Need Help ?</h6>
            <p className="text-white">
              If you would like to learn more about transferring the license to a customer
            </p>
          </div>
        </div>
      </div>
    </div>;
};
export default UpcomingScheduled;

// Nuxtjs/app/pages/dashboard/hr/components/UpcomingScheduled.vue
<template>
  <div class="col-span-1">
    <div class="card">
      <div class="card-header">
        <h6 class="card-title">Upcoming Scheduled</h6>
      </div>

      <div class="card-body">
        <div class="flex flex-col gap-4">
          <div class="flex items-center gap-3">
            <div class="flex flex-col items-center justify-center border rounded-sm size-12 border-default-200">
              <h6 class="text-default-900 font-semibold">28</h6>
              <span class="text-default-500">July</span>
            </div>

            <div>
              <h6 class="mb-1 text-default-900 text-sm font-medium">
                Meeting with Designer
                <small class="px-2 font-medium rounded text-xs py-0.5 bg-default-100 text-default-500">09:57 AM</small>
              </h6>
              <p class="text-default-500">Created by Admin</p>
            </div>
          </div>

          <div class="flex gap-3">
            <div class="flex flex-col items-center justify-center border rounded-sm size-12 border-default-200">
              <h6 class="text-default-800 font-semibold">08</h6>
              <span class="text-default-500">June</span>
            </div>

            <div>
              <h6 class="mb-1 text-default-900 text-sm font-medium">Developing Line Managers Conference <small class="px-2 font-medium rounded text-xs py-0.5 bg-default-100 text-default-500">10:54 AM</small></h6>
              <p class="text-default-500">Created by HR</p>
            </div>
          </div>

          <div class="flex gap-3">
            <div class="flex flex-col items-center justify-center border rounded-sm size-12 border-default-200">
              <h6 class="text-default-800 font-semibold">17</h6>
              <span class="text-default-500">July</span>
            </div>

            <div>
              <h6 class="mb-1 text-default-900 text-sm font-medium">Airplane in Las Vegas <small class="px-2 font-medium rounded text-xs py-0.5 bg-default-100 text-default-500">12:00 PM</small></h6>
              <p class="text-default-500">Created by HR</p>
            </div>
          </div>

          <div class="flex gap-3">
            <div class="flex flex-col items-center justify-center border rounded-sm size-12 border-default-200">
              <h6 class="text-default-800 font-semibold">11</h6>
              <span class="text-default-500">Nov</span>
            </div>

            <div>
              <h6 class="mb-1 text-default-900 text-sm font-medium">Hospitality Project Discuses</h6>
              <p class="text-default-500">Created by Admin</p>
            </div>
          </div>

          <div class="flex gap-3">
            <div class="flex flex-col items-center justify-center border rounded-sm size-12 border-default-200">
              <h6 class="text-default-800 font-semibold">20</h6>
              <span class="text-default-500">Nov</span>
            </div>

            <div>
              <h6 class="mb-1 text-default-900 text-sm font-medium">Gartner Digital Workplace <small class="px-2 font-medium rounded text-xs py-0.5 bg-default-100 text-default-500">03:49 PM</small></h6>
              <p class="text-default-500">Created by HR</p>
            </div>
          </div>

          <div class="flex gap-3">
            <div class="flex flex-col items-center justify-center border rounded-sm size-12 border-default-200">
              <h6 class="text-default-800 font-semibold">04</h6>
              <span class="text-default-500">Dec</span>
            </div>

            <div>
              <h6 class="mb-1 text-default-900 text-sm font-medium">Nordic People Analytics <small class="px-2 font-medium rounded text-xs py-0.5 bg-default-100 text-default-500">11:00 AM</small></h6>
              <p class="text-default-500">Created by Admin</p>
            </div>
          </div>

          <div class="flex gap-3">
            <div class="flex flex-col items-center justify-center border rounded-sm size-12 border-default-200">
              <h6 class="text-default-800 font-semibold">17</h6>
              <span class="text-default-500">Jan</span>
            </div>

            <div>
              <h6 class="mb-1 text-default-900 text-sm font-medium">CIPD Festival of Work <small class="px-2 font-medium rounded text-xs py-0.5 bg-default-100 text-default-500">01:29 PM</small></h6>
              <p class="text-default-500">Created by HR</p>
            </div>
          </div>

          <div class="flex gap-3">
            <div class="flex flex-col items-center justify-center border rounded-sm size-12 border-default-200">
              <h6 class="text-default-800 font-semibold">03</h6>
              <span class="text-default-500">Feb</span>
            </div>

            <div>
              <h6 class="mb-1 text-default-900 text-sm font-medium">HRO Today Forum <small class="px-2 font-medium rounded text-xs py-0.5 bg-default-100 text-default-500">02:15 PM</small></h6>
              <p class="text-default-500">Created by Admin</p>
            </div>
          </div>

          <div class="flex gap-3">
            <div class="flex flex-col items-center justify-center border rounded-sm size-12 border-default-200">
              <h6 class="text-default-800 font-semibold">15</h6>
              <span class="text-default-500">Mar</span>
            </div>
            <div>
              <h6 class="mb-1 text-default-900 text-sm font-medium">
                HR Training Workshop
                <small class="px-2 font-medium rounded text-xs py-0.5 bg-default-100 text-default-500">09:00 AM</small>
              </h6>
              <p class="text-default-500">Created by HR</p>
            </div>
          </div>

          <div class="flex gap-3">
            <div class="flex flex-col items-center justify-center border rounded-sm size-12 border-default-200">
              <h6 class="text-default-800 font-semibold">29</h6>
              <span class="text-default-500">Apr</span>
            </div>
            <div>
              <h6 class="mb-1 text-default-900 text-sm font-medium">
                Marketing Strategy Review
                <small class="px-2 font-medium rounded text-xs py-0.5 bg-default-100 text-default-500">04:45 PM</small>
              </h6>
              <p class="text-default-500">Created by Marketing</p>
            </div>
          </div>

          <div class="flex gap-3">
            <div class="flex flex-col items-center justify-center border rounded-sm size-12 border-default-200">
              <h6 class="text-default-800 font-semibold">10</h6>
              <span class="text-default-500">May</span>
            </div>
            <div>
              <h6 class="mb-1 text-default-900 text-sm font-medium">
                Client Demo Presentation
                <small class="px-2 font-medium rounded text-xs py-0.5 bg-default-100 text-default-500">11:30 AM</small>
              </h6>
              <p class="text-default-500">Created by Admin</p>
            </div>
          </div>
        </div>

        <div class="flex gap-3 p-2 mt-4 rounded-md bg-primary">
          <img :src="support" alt="" class="h-24" />
          <div>
            <h6 class="mb-1 text-base text-white">Need Help ?</h6>
            <p class="text-white">If you would like to learn more about transferring the license to a customer</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import support from '~/assets/images/support.png'
</script>
