// React-JS/src/app/(admin)/(dashboards)/hr/index.jsx
import PageBreadcrumb from '@/components/PageBreadcrumb';
import Activities from './components/Activities';
import ApplicationReceived from './components/ApplicationReceived';
import BirthdayCard from './components/BirthdayCard';
import EmployeDetails from './components/EmployeeDetails';
import EmployeePerformance from './components/EmployeePerformance';
import RecentPayroll from './components/RecentPayroll';
import TotalProjects from './components/TotalProjects';
import UpcomingInterview from './components/UpcomingInterview';
import UpcomingScheduled from './components/UpcomingScheduled';
import PageMeta from '@/components/PageMeta';
const Index = () => {
  return <>
      <PageMeta title="HR" />
      <main>
        <PageBreadcrumb title="HR" subtitle="Dashboard" />
        <Activities />
        <div className="grid lg:grid-cols-2 grid-cols-1 gap-5 mb-5">
          <EmployeDetails />
          <ApplicationReceived />
        </div>
        <div className="grid lg:grid-cols-4 grid-cols-1 gap-5">
          <div className="lg:col-span-3 col-span-1">
            <EmployeePerformance />
            <div className="grid lg:grid-cols-3 col-span-1 gap-5">
              <TotalProjects />
              <UpcomingInterview />
              <div className="col-span-1">
                <BirthdayCard />
                <RecentPayroll />
              </div>
            </div>
          </div>
          <div className="col-span-1">
            <UpcomingScheduled />
          </div>
        </div>
      </main>
    </>;
};
export default Index;

// Vuejs/src/views/dashboard/hr/index.vue
<template>
  <Vertical>
    <PageTitle title="HR" subtitle="Dashboards" />
    <HRWelcome />
    <div class="grid lg:grid-cols-2 grid-cols-1 gap-5 mb-5">
      <SummaryCards />
      <ApplicationReceived />
    </div>
    <div class="grid lg:grid-cols-4 grid-cols-1 gap-5">
      <div class="lg:col-span-3 col-span-1">
        <EmployeePerformance />
        <div class="grid lg:grid-cols-3 col-span-1 gap-5">
          <TotalProjects />
          <UpcomingInterview />
          <RecentPayroll />
        </div>
      </div>
      <UpcomingScheduled />
    </div>
  </Vertical>
</template>

<script setup lang="ts">
import PageTitle from '@/components/PageTitle.vue'
import Vertical from '@/layouts/vertical.vue'
import HRWelcome from './components/HRWelcome.vue'
import SummaryCards from './components/SummaryCards.vue'
import ApplicationReceived from './components/ApplicationReceived.vue'
import EmployeePerformance from './components/EmployeePerformance.vue'
import TotalProjects from './components/TotalProjects.vue'
import UpcomingInterview from './components/UpcomingInterview.vue'
import RecentPayroll from './components/RecentPayroll.vue'
import UpcomingScheduled from './components/UpcomingScheduled.vue'


</script>
