// Vuejs/src/views/hr-management/(leave-manage)/leave-employee/index.vue
<template>
  <Vertical>
    <PageTitle subtitle="Menu" title="Leave Manage (Employee)" />
    <div class="grid lg:grid-cols-4 md:grid-cols-2 grid-cols-1 gap-5 mb-5">
      <StatCard />
    </div>
    <Table />
  </Vertical>
</template>

<script setup lang="ts">
import PageTitle from '@/components/PageTitle.vue'
import Vertical from '@/layouts/vertical.vue'
import StatCard from './components/StatCard.vue'
import Table from './components/Table.vue'

</script>

// Nextjs-JS/src/app/(admin)/(app)/(hr)/leave-employee/page.jsx
import PageBreadcrumb from '@/components/PageBreadcrumb';
import React from 'react';
import LeaveCard from './components/LeaveCard';
import EmpLeave from './components/EmpLeave';
export const metadata = {
  title: 'Leave Manage (Employee)'
};
const Page = () => {
  return <main>
      <PageBreadcrumb title="Leave Manage (Employee)" subtitle="Menu" />
      <LeaveCard />
      <EmpLeave />
    </main>;
};
export default Page;
