// Nextjs-JS/src/app/(admin)/(app)/(hr)/attendance-main/page.jsx
import PageBreadcrumb from '@/components/PageBreadcrumb';
import React from 'react';
import EmployeeReport from './components/EmployeeReport';
import EmployeeReportTabel from './components/EmployeeReportTabel';
export const metadata = {
  title: 'Main Attendance'
};
const Page = () => {
  return <main>
      <PageBreadcrumb title="Main Attendance" subtitle="Menu" />
      <EmployeeReport />
      <EmployeeReportTabel />
    </main>;
};
export default Page;

// Nuxtjs/app/pages/hr-management/(attendance)/attendance-main/index.vue
<template>
  <Vertical>
    <PageTitle subtitle="Menu" title="Main Attendance" />
    <Stat />
    <Table />
  </Vertical>
</template>

<script setup lang="ts">
import PageTitle from '~/components/PageTitle.vue'
import Vertical from '~/layouts/vertical.vue'
import Stat from './components/Stat.vue'
import Table from './components/Table.vue'

usePageTitle('Main Attendance')
</script>
