// React-JS/src/app/(admin)/(app)/(ecommerce)/sellers/components/Sallers.jsx
import IconifyIcon from '@/components/client-wrapper/IconifyIcon';
import { LuEllipsis, LuEye, LuHeart, LuSquarePen, LuTrash2 } from 'react-icons/lu';
import { Link } from 'react-router';
const sellers = [{
  name: 'Themesdesign',
  owner: 'Paula Keenan',
  sales: '4.5k',
  products: 310,
  revenue: '$235.3k',
  heartColor: 'warning',
  iconifyIcon: 'logos:google-adwords'
}, {
  name: 'Nazox Fashion',
  owner: 'Kara Miller',
  sales: '2.3k',
  products: 67,
  revenue: '$235.3k',
  heartColor: 'warning',
  iconifyIcon: 'logos:apple-app-store'
}, {
  name: '4xM Infotech',
  owner: 'Daniel Miller',
  sales: '7.1k',
  products: 138,
  revenue: '$465.9k',
  heartColor: 'default',
  iconifyIcon: 'logos:google-gmail'
}, {
  name: 'Extra Fashion',
  owner: 'Mark Walton',
  sales: '1.9k',
  products: 49,
  revenue: '$198.3k',
  heartColor: 'warning',
  iconifyIcon: 'logos:android'
}, {
  name: 'Nesta Technologies',
  owner: 'William Heineman',
  sales: '4.8k',
  products: 172,
  revenue: '$746.1k',
  heartColor: 'default',
  iconifyIcon: 'logos:figma'
}, {
  name: 'Digitech Galaxy',
  owner: 'David Biggs',
  sales: '9.2k',
  products: 674,
  revenue: '$14.4m',
  heartColor: 'default',
  iconifyIcon: 'logos:meta'
}, {
  name: 'Zoetic Fashion',
  owner: 'Jaqueline Hammes',
  sales: '1.8k',
  products: 112,
  revenue: '$132.4k',
  heartColor: 'default',
  iconifyIcon: 'logos:google'
}, {
  name: 'Force Medicines',
  owner: 'Ashley Uilson',
  sales: '4.1k',
  products: 243,
  revenue: '$861.7k',
  heartColor: 'default',
  iconifyIcon: 'logos:telegram'
}];
const Sallers = () => {
  return <div className="grid lg:grid-cols-4 md:grid-cols-2 grid-cols-1 gap-5">
      {sellers.map((seller, index) => <div key={index} className="card">
          <div className="card-body">
            <div className="flex justify-between gap-5 items-center mb-4">
              <LuHeart className={`size-5 ${seller.heartColor === 'warning' ? 'text-warning fill-warning/10' : 'text-default-500 fill-default-100'}`} />

              <div className="hs-dropdown relative inline-flex">
                <button type="button" className="hs-dropdown-toggle btn size-7.5 bg-default-200 hover:bg-default-600 text-default-500 hover:text-white" aria-haspopup="menu" aria-expanded="false" aria-label="Dropdown" hs-dropdown-placement="bottom-end">
                  <LuEllipsis className="size-4" />
                </button>
                <div className="hs-dropdown-menu" role="menu">
                  <Link className="flex items-center gap-1.5 py-1.5 font-medium px-3 text-default-500 hover:bg-default-150 rounded" to="#">
                    <LuEye className="size-3" />
                    Overview
                  </Link>
                  <Link className="flex items-center gap-1.5 py-1.5 font-medium px-3 text-default-500 hover:bg-default-150 rounded" to="#">
                    <LuSquarePen className="size-3" />
                    Edit
                  </Link>
                  <Link className="flex items-center gap-1.5 py-1.5 font-medium px-3 text-default-500 hover:bg-default-150 rounded" to="#">
                    <LuTrash2 className="size-3" />
                    Delete
                  </Link>
                </div>
              </div>
            </div>

            <div className="flex items-center justify-center mx-auto rounded-full size-16 bg-default-100 outline outline-default-100 outline-offset-4">
              <IconifyIcon icon={seller.iconifyIcon} width="40" height="40" />
            </div>

            <div className="mt-4 mb-6 text-center">
              <h6 className="text-base text-default-800 font-semibold">{seller.name}</h6>
              <p className="text-default-500 text-sm">{seller.owner}</p>
            </div>

            <div className="grid grid-cols-3">
              <div className="text-center p-2 text-sm">
                <h6 className="mb-1 text-default-800 font-semibold">{seller.sales}</h6>
                <p className="text-default-500">Sales</p>
              </div>

              <div className="text-center p-2 border-e border-s border-dashed border-default-200 text-sm">
                <h6 className="mb-1 text-default-800 font-semibold">{seller.products}</h6>
                <p className="text-default-500">Product</p>
              </div>

              <div className="text-center p-2 text-sm">
                <h6 className="mb-1 text-default-800 font-semibold">{seller.revenue}</h6>
                <p className="text-default-500">Revenue</p>
              </div>
            </div>
          </div>
        </div>)}
    </div>;
};
export default Sallers;

// Angular/src/app/views/ecommerce/sallers/sallers.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { NgIcon } from "@ng-icons/core";
import { SallersModal } from "./components/sallers-modal/sallers-modal";
import { Pagination } from "../../../components/pagination/pagination";
import { PageTitle } from "../../../components/page-title/page-title";
import { RouterLink } from '@angular/router';

type CardItem = {
  name: string;
  owner: string;
  icon: string;
  heartFilled?: boolean;
  stats: {
    label: string;
    value: string;
  }[];
}

@Component({
  selector: 'app-sallers',
  imports: [NgIcon, SallersModal, Pagination, PageTitle, RouterLink],
  templateUrl: './sallers.html',
  styles: ``,
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class Sallers {

  cardsData: CardItem[] = [
    {
      name: 'Themesdesign',
      owner: 'Paula Keenan',
      icon: 'logos:google-adwords',
      heartFilled: true,
      stats: [
        { label: 'Sales', value: '4.5k' },
        { label: 'Product', value: '310' },
        { label: 'Revenue', value: '$235.3k' },
      ],
    },
    {
      name: 'Nazox Fashion',
      owner: 'Kara Miller',
      icon: 'logos:apple-app-store',
      heartFilled: true,
      stats: [
        { label: 'Sales', value: '2.3k' },
        { label: 'Product', value: '67' },
        { label: 'Revenue', value: '$235.3k' },
      ],
    },
    {
      name: '4xM Infotech',
      owner: 'Daniel Miller',
      icon: 'logos:google-gmail',
      heartFilled: false,
      stats: [
        { label: 'Sales', value: '7.1k' },
        { label: 'Product', value: '138' },
        { label: 'Revenue', value: '$465.9k' },
      ],
    },
    {
      name: 'Extra Fashion',
      owner: 'Mark Walton',
      icon: 'logos:android-icon',
      heartFilled: true,
      stats: [
        { label: 'Sales', value: '1.9k' },
        { label: 'Product', value: '49' },
        { label: 'Revenue', value: '$198.3k' },
      ],
    },
    {
      name: 'Nesta Technologies',
      owner: 'William Heineman',
      icon: 'logos:figma',
      heartFilled: true,
      stats: [
        { label: 'Sales', value: '4.8k' },
        { label: 'Product', value: '172' },
        { label: 'Revenue', value: '$746.1k' },
      ],
    },
    {
      name: 'Digitech Galaxy',
      owner: 'David Biggs',
      icon: 'logos:meta-icon',
      heartFilled: false,
      stats: [
        { label: 'Sales', value: '9.2k' },
        { label: 'Product', value: '674' },
        { label: 'Revenue', value: '$14.4m' },
      ],
    },
    {
      name: 'Zoetic Fashion',
      owner: 'Jaqueline Hammes',
      icon: 'logos:google-icon',
      heartFilled: false,
      stats: [
        { label: 'Sales', value: '1.8k' },
        { label: 'Product', value: '112' },
        { label: 'Revenue', value: '$132.4k' },
      ],
    },
    {
      name: 'Force Medicines',
      owner: 'Ashley Uilson',
      icon: 'logos:telegram',
      heartFilled: false,
      stats: [
        { label: 'Sales', value: '4.1k' },
        { label: 'Product', value: '243' },
        { label: 'Revenue', value: '$861.7k' },
      ],
    },
  ];

}
