// Vuejs/src/views/apps/calendar/index.vue
<template>
  <Vertical>
    <PageTitle subtitle="Menu" title="Calendar" />
    <div class="grid lg:grid-cols-4 gap-5">
      <Calendar />
      <Event />
    </div>
  </Vertical>
</template>

<script setup lang="ts">
import PageTitle from '@/components/PageTitle.vue'
import Vertical from '@/layouts/vertical.vue'
import Calendar from './components/Calendar.vue'
import Event from './components/Event.vue'
</script>

// React-JS/src/app/(admin)/(app)/calendar/index.jsx
import PageBreadcrumb from '@/components/PageBreadcrumb';
import PageMeta from '@/components/PageMeta';
import Calender from './components/Calender';
const Index = () => {
  return <>
      <PageMeta title="Calendar" />
      <main>
        <PageBreadcrumb title="Calendar" subtitle="Menu" />
        <div className="grid lg:grid-cols-4 gap-5">
          <Calender />
        </div>
      </main>
    </>;
};
export default Index;
