// Vuejs/src/views/(pages)/pricing/components/Pricing.vue
<template>
  <div class="grid lg:grid-cols-4 md:grid-cols-2 gap-5 mb-6">
    <div v-for="plan in plans" :key="plan.id" class="card relative overflow-hidden">
      <div class="card-body">
        <div v-if="plan.badge" class="size-16 absolute top-0 end-0">
          <div class="absolute bg-primary text-center w-42.5 text-white py-1 transform rotate-45 top-6 -end-12 font-semibold">
            {{ plan.badge }}
          </div>
        </div>
        <h5 class="mb-2 flex items-center gap-1.5">
          <Icon :icon="plan.icon" :class="`${plan.color} size-5`"></Icon>
          <span class="text-lg font-semibold text-default-800">
            {{ plan.title }}
          </span>
        </h5>
        <p class="mb-4 text-default-500">{{ plan.description }}</p>
        <h1 class="mb-4 text-4xl text-default-800 font-normal">
          <span class="text-default-400">$</span>{{ plan.price }}
          <small class="text-base text-default-500">/Monthly</small>
        </h1>
        <button type="button" class="btn border w-full border-dashed border-primary bg-transparent text-primary hover:bg-primary/20">Purchase Now</button>
        <ul class="mt-5 flex flex-col gap-3 text-sm">
          <li v-for="(feature, idx) in plan.features" :key="idx" class="flex items-center gap-2.5">
            <Icon :icon="feature.included ? 'lucide:check-check' : 'lucide:x'" :class="feature.included ? 'size-4 text-success' : 'size-4 text-danger'" />
            <span v-if="feature.included" class="text-default-900" v-html="feature.label"></span>
            <del v-else class="text-default-500" v-html="feature.label"></del>
          </li>
        </ul>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { Icon } from '@iconify/vue'

type Feature = {
  label: string
  included: boolean
}

type Plan = {
  id: number
  title: string
  description: string
  price: string
  icon: string
  color: string
  badge?: string
  features: Feature[]
}

const plans: Plan[] = [
  {
    id: 1,
    title: 'Lite',
    description: 'Perfect plan for Lite',
    price: '9.99',
    icon: 'lucide:goal',
    color: 'text-success',
    features: [
      { label: '<b>3</b> Projects', included: true },
      { label: '<b>299</b> Customers', included: true },
      { label: 'Scalable Bandwidth', included: true },
      { label: '<b>0</b> No Team Account', included: true },
      { label: 'In app messaging', included: false },
      { label: '5 FTP Login', included: false },
      { label: 'Detailed Analytics', included: false },
      { label: 'Custom Domain', included: false },
      { label: 'Smart Workflow', included: false },
      { label: 'IQ test', included: false }
    ]
  },
  {
    id: 2,
    title: 'Professional',
    description: 'For users who want to do more.',
    price: '29.99',
    icon: 'lucide:graduation-cap',
    color: 'text-secondary',
    features: [
      { label: '<b>3</b> Projects', included: true },
      { label: '<b>299</b> Customers', included: true },
      { label: 'Scalable Bandwidth', included: true },
      { label: '<b>3</b> No Team Account', included: true },
      { label: 'In app messaging', included: true },
      { label: '5 FTP Login', included: false },
      { label: 'Detailed Analytics', included: false },
      { label: 'Custom Domain', included: false },
      { label: 'Smart Workflow', included: false },
      { label: 'IQ test', included: false }
    ]
  },
  {
    id: 3,
    title: 'Enterprise',
    description: 'Run your company on your teams',
    price: '39.99',
    icon: 'lucide:crown',
    color: 'text-primary',
    badge: '25% Sale',
    features: [
      { label: '<b>3</b> Projects', included: true },
      { label: '<b>299</b> Customers', included: true },
      { label: 'Scalable Bandwidth', included: true },
      { label: '<b>3</b> No Team Account', included: true },
      { label: 'In app messaging', included: true },
      { label: '5 FTP Login', included: true },
      { label: 'Detailed Analytics', included: true },
      { label: 'Custom Domain', included: false },
      { label: 'Smart Workflow', included: false },
      { label: 'IQ test', included: false }
    ]
  },
  {
    id: 4,
    title: 'Unlimited',
    description: 'Your entire team in one place',
    price: '49.99',
    icon: 'lucide:luggage',
    color: 'text-danger',
    features: [
      { label: '<b>3</b> Projects', included: true },
      { label: '<b>299</b> Customers', included: true },
      { label: 'Scalable Bandwidth', included: true },
      { label: '<b>3</b> No Team Account', included: true },
      { label: 'In app messaging', included: true },
      { label: '5 FTP Login', included: true },
      { label: 'Detailed Analytics', included: true },
      { label: 'Custom Domain', included: true },
      { label: 'Smart Workflow', included: true },
      { label: 'IQ test', included: true }
    ]
  }
]
</script>

// React-JS/src/app/(landing)/onepage-landing/components/Pricing.jsx
import React from 'react';
import { LuCheckCheck, LuCrown, LuGoal, LuGraduationCap, LuLuggage, LuX } from 'react-icons/lu';
const pricingPlans = [{
  id: 1,
  title: 'Lite',
  description: 'Perfect plan for Lite',
  price: '9.99',
  period: '/Monthly',
  icon: LuGoal,
  iconColor: 'text-success',
  buttonText: 'Purchase Now',
  features: [{
    name: '<b>3</b> Projects',
    included: true
  }, {
    name: '<b>299 </b>Customers',
    included: true
  }, {
    name: 'Scalable Bandwidth',
    included: true
  }, {
    name: 'No Team Account',
    included: true
  }, {
    name: 'In app messaging',
    included: false
  }, {
    name: '5 FTP Login',
    included: false
  }, {
    name: 'Detailed Analytics',
    included: false
  }, {
    name: 'Custom Domain',
    included: false
  }, {
    name: 'Smart Workflow',
    included: false
  }, {
    name: 'IQ test',
    included: false
  }]
}, {
  id: 2,
  title: 'Professional',
  description: 'For users who want to do more.',
  price: '29.99',
  period: '/Monthly',
  icon: LuGraduationCap,
  iconColor: 'text-secondary',
  buttonText: 'Purchase Now',
  features: [{
    name: '<b>3</b> Projects',
    included: true
  }, {
    name: '<b>299</b> Customers',
    included: true
  }, {
    name: 'Scalable Bandwidth',
    included: true
  }, {
    name: '<b>3</b> No Team Account',
    included: true
  }, {
    name: 'In app messaging',
    included: true
  }, {
    name: '5 FTP Login',
    included: false
  }, {
    name: 'Detailed Analytics',
    included: false
  }, {
    name: 'Custom Domain',
    included: false
  }, {
    name: 'Smart Workflow',
    included: false
  }, {
    name: 'IQ test',
    included: false
  }]
}, {
  id: 3,
  title: 'Enterprise',
  description: 'Run your company on your teams',
  price: '39.99',
  period: '/Monthly',
  icon: LuCrown,
  iconColor: 'text-primary',
  buttonText: 'Purchase Now',
  highlight: '25% Sale',
  features: [{
    name: '<b>3</b> Projects',
    included: true
  }, {
    name: '<b>299</b> Customers',
    included: true
  }, {
    name: 'Scalable Bandwidth',
    included: true
  }, {
    name: '<b>3</b> No Team Account',
    included: true
  }, {
    name: 'In app messaging',
    included: true
  }, {
    name: '5 FTP Login',
    included: true
  }, {
    name: 'Detailed Analytics',
    included: true
  }, {
    name: 'Custom Domain',
    included: false
  }, {
    name: 'Smart Workflow',
    included: false
  }, {
    name: 'IQ test',
    included: false
  }]
}, {
  id: 4,
  title: 'Unlimited',
  description: 'Your entire team in one place',
  price: '49.99',
  period: '/Monthly',
  icon: LuLuggage,
  iconColor: 'text-danger',
  buttonText: 'Purchase Now',
  features: [{
    name: '<b>3</b> Projects',
    included: true
  }, {
    name: '<b>299</b> Customers',
    included: true
  }, {
    name: 'Scalable Bandwidth',
    included: true
  }, {
    name: '<b>3</b> No Team Account',
    included: true
  }, {
    name: 'In app messaging',
    included: true
  }, {
    name: '5 FTP Login',
    included: true
  }, {
    name: 'Detailed Analytics',
    included: true
  }, {
    name: 'Custom Domain',
    included: true
  }, {
    name: 'Smart Workflow',
    included: true
  }, {
    name: 'IQ test',
    included: true
  }]
}];
const Pricing = () => {
  return <section id="pricing" className="relative lg:pb-24 md:pb-18 pb-12">
      <div className="container">
        <div className="flex flex-col gap-y-16">
          <div className="text-center lg:w-3xl mx-auto">
            <h1 className="mb-4 leading-relaxed text-4xl font-semibold text-default-800">
              Tailored Website Design Package
            </h1>
            <p className="text-lg text-default-500">
              A good web design package will include designing a logo, integration with local SEO,
              linking a site to a social media presence, and more.
            </p>
          </div>

          <div className="grid lg:grid-cols-4 md:grid-cols-2 gap-5 mb-6">
            {pricingPlans.map(plan => <div key={plan.id} className="card relative overflow-hidden">
                <div className="card-body">
                  {plan.highlight && <div className="size-16 absolute top-0 end-0">
                      <div className="absolute bg-primary text-center w-42.5 text-white py-1 transform rotate-45 top-6 -end-12 font-semibold">
                        {plan.highlight}
                      </div>
                    </div>}

                  <h5 className="mb-2 flex items-center gap-1.5">
                    <plan.icon className={`${plan.iconColor} size-5`} />
                    <span className="text-lg font-semibold text-default-800">{plan.title}</span>
                  </h5>

                  <p className="mb-4 text-default-500">{plan.description}</p>
                  <h1 className="mb-4 text-4xl text-default-800 font-normal">
                    <span className="text-default-400">$</span>
                    {plan.price}
                    <small className="text-base text-default-500">{plan.period}</small>
                  </h1>

                  <button type="button" className="btn border w-full border-dashed border-primary bg-transparent text-primary hover:bg-primary/20">
                    {plan.buttonText}
                  </button>

                  <ul className="mt-5 flex flex-col gap-3 text-sm">
                    {plan.features.map((feature, i) => <li key={i} className="flex items-center gap-2.5">
                        {feature.included ? <LuCheckCheck className="size-4 text-success" /> : <LuX className="size-4 text-danger" />}
                        {feature.included ? <span className={feature.included ? 'text-default-900' : 'text-default-500'} dangerouslySetInnerHTML={{
                    __html: feature.name
                  }} /> : <del className="text-default-500">{feature.name}</del>}
                      </li>)}
                  </ul>
                </div>
              </div>)}
          </div>
        </div>
      </div>
    </section>;
};
export default Pricing;
