// React-JS/src/app/(landing)/product-landing/components/Product.jsx
import img16 from '@/assets/images/landing/img-16.png';
import img17 from '@/assets/images/landing/img-17.png';
import img18 from '@/assets/images/landing/img-18.png';
import img19 from '@/assets/images/landing/img-19.png';
import { LuStar } from 'react-icons/lu';
const products = [{
  id: 1,
  name: 'Green Sneakers Skate',
  price: 299.99,
  rating: 4.8,
  image: img16
}, {
  id: 2,
  name: 'Nike Running Shoes',
  price: 129.49,
  rating: 4.4,
  image: img17
}, {
  id: 3,
  name: 'Nike Air Max Sneakers Shoe',
  price: 149.99,
  rating: 4.9,
  image: img18
}, {
  id: 4,
  name: 'Dunk Sneakers Skate Shoe',
  price: 174.65,
  rating: 4.6,
  image: img19
}];
const Product = () => {
  return <section id="product" className="relative lg:py-32 py-20">
      <div className="container">
        <div className="lg:w-3xl mx-auto text-center">
          <h1 className="leading-normal capitalize text-4xl font-semibold text-default-800">
            Our Latest Product
          </h1>
        </div>

        <div className="grid lg:grid-cols-4 md:grid-cols-2 grid-cols-1 gap-5 mt-12">
          {products.map(product => <div key={product.id} className="card bg-gradient-to-b from-default-100 to-default-50/40 shadow-none rounded-md">
              <div className="card-body">
                <img src={product.image} alt={product.name} className="mx-auto h-52 object-contain" />

                <div className="mt-3">
                  <p className="mb-3 flex items-center gap-1 text-sm">
                    <LuStar className="text-amber-500 size-4" />({product.rating})
                  </p>

                  <h5 className="text-lg font-semibold text-default-800">{product.name}</h5>

                  <div className="flex justify-between items-center mt-3">
                    <h6 className="text-base font-semibold text-default-800">
                      ${product.price.toFixed(2)}
                    </h6>
                    <button type="button" className="btn btn-sm bg-primary text-white">
                      Add to Cart
                    </button>
                  </div>
                </div>
              </div>
            </div>)}
        </div>
      </div>
    </section>;
};
export default Product;

// Nuxtjs/app/pages/landing/product/components/Product.vue
<template>
  <section id="product" class="relative lg:py-32 py-20">
    <div class="container">
      <div class="lg:w-3xl mx-auto text-center">
        <h1 class="leading-normal capitalize text-4xl font-semibold text-default-800">Our Latest Product</h1>
      </div>
      <div class="grid lg:grid-cols-4 md:grid-cols-2 grid-cols-1 gap-5 mt-12">
        <div class="card bg-gradient-to-b from-default-100 to-default-50/40 shadow-none rounded-md">
          <div class="card-body">
            <img :src="img16" alt="" class="mx-auto h-52" />
            <div class="mt-3">
              <p class="mb-3 flex items-center gap-1"><Icon icon="lucide:star" class="text-amber-500 size-4"></Icon> (4.8)</p>
              <h5 class="text-lg font-semibold text-default-800">
                <a href="#">Green Sneakers Skate</a>
              </h5>
              <div class="flex justify-between items-center mt-3">
                <h6 class="text-base font-semibold text-default-800">$299.99</h6>
                <div>
                  <button type="button" class="btn btn-sm bg-primary text-white">Add to Cart</button>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="card bg-gradient-to-b from-default-100 to-default-50/40 shadow-none rounded-md">
          <div class="card-body">
            <img :src="img17" alt="" class="mx-auto h-52" />
            <div class="mt-3">
              <p class="mb-3 flex items-center gap-1"><Icon icon="lucide:star" class="text-amber-500 size-4"></Icon> (4.4)</p>
              <h5 class="text-lg font-semibold text-default-800">
                <a href="#">Nike Running Shoes</a>
              </h5>
              <div class="flex justify-between items-center mt-3">
                <h6 class="text-base font-semibold text-default-800">$129.49</h6>
                <div>
                  <button type="button" class="btn btn-sm bg-primary text-white">Add to Cart</button>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="card bg-gradient-to-b from-default-100 to-default-50/40 shadow-none rounded-md">
          <div class="card-body">
            <img :src="img18" alt="" class="mx-auto h-52" />
            <div class="mt-3">
              <p class="mb-3 flex items-center gap-1"><Icon icon="lucide:star" class="text-amber-500 size-4"></Icon> (4.9)</p>
              <h5 class="text-lg font-semibold text-default-800">
                <a href="#">Nike Air Max Sneakers Shoe</a>
              </h5>
              <div class="flex justify-between items-center mt-3">
                <h6 class="text-base font-semibold text-default-800">$149.99</h6>
                <div>
                  <button type="button" class="btn btn-sm bg-primary text-white">Add to Cart</button>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="card bg-gradient-to-b from-default-100 to-default-50/40 shadow-none rounded-md">
          <div class="card-body">
            <img :src="img19" alt="" class="mx-auto h-52" />
            <div class="mt-3">
              <p class="mb-3 flex items-center gap-1"><Icon icon="lucide:star" class="text-amber-500 size-4"></Icon> (4.6)</p>
              <h5 class="text-lg font-semibold text-default-800">
                <a href="#">Dunk Sneakers Skate shoe</a>
              </h5>
              <div class="flex justify-between items-center mt-3">
                <h6 class="text-base font-semibold text-default-800">$174.65</h6>
                <div>
                  <button type="button" class="btn btn-sm bg-primary text-white">Add to Cart</button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
import { Icon } from '@iconify/vue'
import img16 from '~/assets/images/landing/img-16.png'
import img17 from '~/assets/images/landing/img-17.png'
import img18 from '~/assets/images/landing/img-18.png'
import img19 from '~/assets/images/landing/img-19.png'
</script>
