// Vuejs/src/views/landing/one-page/index.vue
<template>
  <Header />
  <Hero />
  <Feature />
  <About />
  <Pricing />
  <Contact />
  <Footer />
</template>

<script setup lang="ts">
import About from './components/About.vue'
import Contact from './components/Contact.vue'
import Feature from './components/Feature.vue'
import Footer from './components/Footer.vue'
import Header from './components/Header.vue'
import Hero from './components/Hero.vue'
import Pricing from './components/Pricing.vue'
</script>

// Angular/src/app/views/landing/onepage/onepage.ts
import { Component } from '@angular/core';
import { Header } from "./components/header/header";
import { Hero } from "./components/hero/hero";
import { Feature } from "./components/feature/feature";
import { Services } from "./components/services/services";
import { About } from "./components/about/about";
import { Pricing } from "./components/pricing/pricing";
import { Contact } from "./components/contact/contact";
import { Footer } from "./components/footer/footer";

@Component({
  selector: 'app-onepage',
  imports: [Header, Hero, Feature, Services, About, Pricing, Contact, Footer],
  templateUrl: './onepage.html',
  styles: ``
})
export class Onepage {

}
