// React-JS/src/app/(admin)/(dashboards)/hr/components/UpcomingInterview.jsx
import user5 from '@/assets/images/user/avatar-5.png';
import user1 from '@/assets/images/user/user-1.jpg';
import user2 from '@/assets/images/user/user-2.jpg';
import user3 from '@/assets/images/user/user-3.jpg';
import SimplebarClient from '@/components/client-wrapper/SimplebarClient';
import { Link } from 'react-router';
import { LuCalendar, LuClock, LuEllipsisVertical } from 'react-icons/lu';
const interviews = [{
  id: 1,
  name: 'James Krogman',
  email: 'james@tailwick.com',
  image: user1,
  date: '25 Nov',
  time: '02:41 pm',
  status: 'Confirm',
  statusColor: 'border-success/40 text-success'
}, {
  id: 2,
  name: 'Michael Scott',
  email: 'michaelScott@tailwick.com',
  image: user2,
  date: '05 Dec',
  time: '01:23 pm',
  status: 'Re-scheduled',
  statusColor: 'border-primary/40 text-primary'
}, {
  id: 3,
  name: 'Denise Ledford',
  email: 'ledford@tailwick.com',
  image: user3,
  date: '27 Nov',
  time: '11:59 pm',
  status: 'Scheduled',
  statusColor: 'border-secondary/40 text-secondary'
}, {
  id: 4,
  name: 'Gladys Smith',
  email: 'gap-4@tailwick.com',
  image: user5,
  date: '07 Dec',
  time: '05:19 pm',
  status: 'Cancelled',
  statusColor: 'border-danger/40 text-danger'
}];
const UpcomingInterview = () => {
  return <div className="col-span-1">
      <div className="card z-10">
        <div className="card-header">
          <h6 className="card-title">Upcoming Interview</h6>
        </div>

        <SimplebarClient className="h-98">
          <div className="card-body">
            <div className="flex flex-col gap-3">
              {interviews.map(interview => <div key={interview.id} className="border rounded-md border-default-200">
                  <div className="flex justify-between items-center p-2 border-b border-default-200">
                    <div className="flex flex-wrap items-center gap-3">
                      <div className="rounded-full size-10">
                        <img src={interview.image} alt={interview.name} className="rounded-full" />
                      </div>
                      <div className="text-sm">
                        <h6 className="mb-1 text-default-800 font-semibold">
                          <Link to="#">{interview.name}</Link>
                        </h6>
                        <p className="text-default-500">{interview.email}</p>
                      </div>
                    </div>

                    <div className="hs-dropdown relative inline-flex">
                      <button type="button" className="hs-dropdown-toggle btn size-7.5 hover:bg-default-150 text-default-500" aria-haspopup="menu" aria-expanded="false" aria-label="Dropdown" hs-dropdown-placement="bottom-end">
                        <LuEllipsisVertical className="size-4" />
                      </button>

                      <div className="hs-dropdown-menu transition-[opacity,margin] duration hs-dropdown-open:opacity-100 opacity-0 hidden min-w-40 card z-60 mt-2 p-2" role="menu">
                        <div className="flex flex-col gap-y-1 text-sm">
                          <Link className="py-1.5 font-medium px-3 text-default-500 hover:bg-default-150 rounded" to="#">
                            Overview
                          </Link>
                          <Link className="py-1.5 font-medium px-3 text-default-500 hover:bg-default-150 rounded" to="#">
                            Edit
                          </Link>
                          <Link className="py-1.5 font-medium px-3 text-default-500 hover:bg-default-150 rounded" to="#">
                            Delete
                          </Link>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div className="p-2">
                    <div className="flex justify-between items-center gap-3 text-sm">
                      <div className="flex gap-3 items-center text-default-500">
                        <div className="flex items-center">
                          <LuCalendar className="size-4 me-1.5" />
                          <span>{interview.date}</span>
                        </div>
                        <div className="flex items-center">
                          <LuClock className="size-4 me-1.5" />
                          <span className="uppercase">{interview.time}</span>
                        </div>
                      </div>
                      <div>
                        <span className={`inline-flex items-center gap-x-1.5 py-0.5 px-2 rounded text-xs font-normal border ${interview.statusColor}`}>
                          {interview.status}
                        </span>
                      </div>
                    </div>
                  </div>
                </div>)}
            </div>
          </div>
        </SimplebarClient>
      </div>
    </div>;
};
export default UpcomingInterview;

// Vuejs/src/views/dashboard/hr/components/UpcomingInterview.vue
<template>
  <div class="col-span-1">
    <div class="card z-10">
      <div class="card-header">
        <h6 class="card-title">Upcoming Interview</h6>
      </div>
      <simplebar class="h-98" data-simplebar>
        <div class="card-body">
          <div class="flex flex-col gap-3">
            <div class="border rounded-md border-default-200">
              <div class="flex justify-between items-center p-2 border-b border-default-200">
                <div class="flex flex-wrap items-center gap-3">
                  <div class="rounded-full size-10">
                    <img :src="user1" alt="" class="rounded-full" />
                  </div>
                  <div class="text-sm">
                    <h6 class="mb-1 text-default-800 font-semibold"><RouterLink to="">James Krogman</RouterLink></h6>
                    <p class="text-default-500">james@tailwick.com</p>
                  </div>
                </div>
                <div class="hs-dropdown relative inline-flex">
                  <button type="button" class="hs-dropdown-toggle btn size-7.5 hover:bg-default-150 text-default-500" aria-haspopup="menu" aria-expanded="false" aria-label="Dropdown" hs-dropdown-placement="bottom-end">
                    <Icon icon="lucide:ellipsis-vertical" class="iconify size-4"></Icon>
                  </button>
                  <div class="hs-dropdown-menu transition-[opacity,margin] duration hs-dropdown-open:opacity-100 opacity-0 hidden min-w-40 card z-60 mt-2 p-2" role="menu">
                    <div class="flex flex-col gap-y-1 text-sm">
                      <RouterLink class="py-1.5 font-medium px-3 text-default-500 hover:bg-default-150 rounded" to=""> Overview </RouterLink>
                      <RouterLink class="py-1.5 font-medium px-3 text-default-500 hover:bg-default-150 rounded" to=""> Edit </RouterLink>
                      <RouterLink class="py-1.5 font-medium px-3 text-default-500 hover:bg-default-150 rounded" to=""> Delete </RouterLink>
                    </div>
                  </div>
                </div>
              </div>
              <div class="p-2">
                <div class="flex justify-between items-center gap-3 text-sm">
                  <div class="flex gap-3 items-center text-default-500">
                    <div class="flex items-center">
                      <Icon icon="lucide:calendar" class="size-4 me-1.5"></Icon>
                      <span>25 Nov</span>
                    </div>
                    <div class="flex items-center text-default-500">
                      <Icon icon="lucide:clock" class="size-4 me-1.5"></Icon>
                      <span class="uppercase">02:41 pm</span>
                    </div>
                  </div>
                  <div>
                    <span class="inline-flex items-center gap-x-1.5 py-0.5 px-2 rounded text-xs font-normal border border-success/40 text-success">Confirm</span>
                  </div>
                </div>
              </div>
            </div>
            <div class="border rounded-md border-default-200">
              <div class="flex justify-between items-center p-2 border-b border-default-200">
                <div class="flex flex-wrap items-center gap-3">
                  <div class="rounded-full size-10">
                    <img :src="user2" alt="" class="rounded-full" />
                  </div>
                  <div class="text-sm">
                    <h6 class="mb-1 text-default-800 font-semibold"><RouterLink to="">Michael Scott</RouterLink></h6>
                    <p class="text-default-500">michaelScott@tailwick.com</p>
                  </div>
                </div>
                <div class="hs-dropdown relative inline-flex">
                  <button type="button" class="hs-dropdown-toggle btn size-7.5 hover:bg-default-150 text-default-500" aria-haspopup="menu" aria-expanded="false" aria-label="Dropdown" hs-dropdown-placement="bottom-end">
                    <Icon icon="lucide:ellipsis-vertical" class="iconify size-4"></Icon>
                  </button>
                  <div class="hs-dropdown-menu transition-[opacity,margin] duration hs-dropdown-open:opacity-100 opacity-0 hidden min-w-40 card z-140 mt-2 p-2" role="menu">
                    <div class="flex flex-col gap-y-1 text-sm">
                      <RouterLink class="py-1.5 font-medium px-3 text-default-500 hover:bg-default-150 rounded" to=""> Overview </RouterLink>
                      <RouterLink class="py-1.5 font-medium px-3 text-default-500 hover:bg-default-150 rounded" to=""> Edit </RouterLink>
                      <RouterLink class="py-1.5 font-medium px-3 text-default-500 hover:bg-default-150 rounded" to=""> Delete </RouterLink>
                    </div>
                  </div>
                </div>
              </div>
              <div class="p-2">
                <div class="flex justify-between items-center gap-3 text-sm">
                  <div class="flex gap-3 items-center">
                    <div class="flex items-center text-default-500">
                      <Icon icon="lucide:calendar" class="size-4 me-1.5"></Icon>
                      <span>05 Dec</span>
                    </div>
                    <div class="flex items-center text-default-500">
                      <Icon icon="lucide:clock" class="size-4 me-1.5"></Icon>
                      <span class="uppercase">01:23 pm</span>
                    </div>
                  </div>
                  <div>
                    <span class="inline-flex items-center gap-x-1.5 py-0.5 px-2 rounded text-xs font-normal border border-primary/40 text-primary">Re-scheduled</span>
                  </div>
                </div>
              </div>
            </div>
            <div class="border rounded-md border-default-200">
              <div class="flex justify-between items-center p-2 border-b border-default-200">
                <div class="flex flex-wrap items-center gap-3">
                  <div class="rounded-full size-10">
                    <img :src="user3" alt="" class="rounded-full" />
                  </div>
                  <div class="text-sm">
                    <h6 class="mb-1 text-default-800 font-semibold"><RouterLink to="">Denise Ledford</RouterLink></h6>
                    <p class="text-default-500">ledford@tailwick.com</p>
                  </div>
                </div>
                <div class="hs-dropdown relative inline-flex">
                  <button type="button" class="hs-dropdown-toggle btn size-7.5 hover:bg-default-150 text-default-500" aria-haspopup="menu" aria-expanded="false" aria-label="Dropdown" hs-dropdown-placement="bottom-end">
                    <Icon icon="lucide:ellipsis-vertical" class="iconify size-4"></Icon>
                  </button>
                  <div class="hs-dropdown-menu transition-[opacity,margin] duration hs-dropdown-open:opacity-100 opacity-0 hidden min-w-40 card z-140 mt-2 p-2" role="menu">
                    <div class="flex flex-col gap-y-1 text-sm">
                      <RouterLink class="py-1.5 font-medium px-3 text-default-500 hover:bg-default-150 rounded" to=""> Overview </RouterLink>
                      <RouterLink class="py-1.5 font-medium px-3 text-default-500 hover:bg-default-150 rounded" to=""> Edit </RouterLink>
                      <RouterLink class="py-1.5 font-medium px-3 text-default-500 hover:bg-default-150 rounded" to=""> Delete </RouterLink>
                    </div>
                  </div>
                </div>
              </div>
              <div class="p-2">
                <div class="flex justify-between items-center gap-3 text-sm">
                  <div class="flex gap-3 items-center">
                    <div class="flex items-center text-default-500">
                      <Icon icon="lucide:calendar" class="size-4 me-1.5"></Icon>
                      <span> 27 Nov</span>
                    </div>
                    <div class="flex items-center text-default-500">
                      <Icon icon="lucide:clock" class="size-4 me-1.5"></Icon>
                      <span class="uppercase">11:59 pm</span>
                    </div>
                  </div>
                  <div>
                    <span class="inline-flex items-center gap-x-1.5 py-0.5 px-2 rounded text-xs font-normal border border-secondary/40 text-secondary">Scheduled</span>
                  </div>
                </div>
              </div>
            </div>
            <div class="border rounded-md border-default-200">
              <div class="flex justify-between items-center p-2 border-b border-default-200">
                <div class="flex flex-wrap items-center gap-3">
                  <div class="rounded-full size-10">
                    <img :src="avatar" alt="" class="rounded-full" />
                  </div>
                  <div>
                    <h6 class="mb-1 text-default-800 font-semibold"><RouterLink to="">Gladys Smith</RouterLink></h6>
                    <p class="text-default-500">gap-4@tailwick.com</p>
                  </div>
                </div>
                <div class="hs-dropdown relative inline-flex">
                  <button type="button" class="hs-dropdown-toggle btn size-7.5 hover:bg-default-150 text-default-500" aria-haspopup="menu" aria-expanded="false" aria-label="Dropdown" hs-dropdown-placement="bottom-end">
                    <Icon icon="lucide:ellipsis-vertical" class="iconify size-4"></Icon>
                  </button>
                  <div class="hs-dropdown-menu transition-[opacity,margin] duration hs-dropdown-open:opacity-100 opacity-0 hidden min-w-40 card z-140 mt-2 p-2" role="menu">
                    <div class="flex flex-col gap-y-1 text-sm">
                      <RouterLink class="py-1.5 font-medium px-3 text-default-500 hover:bg-default-150 rounded" to=""> Overview </RouterLink>
                      <RouterLink class="py-1.5 font-medium px-3 text-default-500 hover:bg-default-150 rounded" to=""> Edit </RouterLink>
                      <RouterLink class="py-1.5 font-medium px-3 text-default-500 hover:bg-default-150 rounded" to=""> Delete </RouterLink>
                    </div>
                  </div>
                </div>
              </div>
              <div class="p-2">
                <div class="flex justify-between items-center gap-3 text-sm">
                  <div class="flex gap-3 items-center">
                    <div class="flex items-center text-default-500">
                      <Icon icon="lucide:calendar" class="size-4 me-1.5"></Icon>
                      <span> 07 Dec</span>
                    </div>
                    <div class="flex items-center text-default-500">
                      <Icon icon="lucide:clock" class="size-4 me-1.5"></Icon>
                      <span class="uppercase">05:19 pm</span>
                    </div>
                  </div>
                  <div>
                    <span class="inline-flex items-center gap-x-1.5 py-0.5 px-2 rounded text-xs font-normal border border-danger/40 text-danger">Cancelled</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </simplebar>
    </div>
  </div>
</template>

<script setup lang="ts">
import { Icon } from '@iconify/vue'
import simplebar from 'simplebar-vue'
import user1 from '@/assets/images/user/user-1.jpg'
import user2 from '@/assets/images/user/user-2.jpg'
import user3 from '@/assets/images/user/user-3.jpg'
import avatar from '@/assets/images/user/avatar-5.png'
import { RouterLink } from 'vue-router'
</script>
