// Nuxtjs/app/pages/dashboard/hr/index.vue
<template>
  <Vertical>
    <PageTitle title="HR" subtitle="Dashboards" />
    <HRWelcome />
    <div class="grid lg:grid-cols-2 grid-cols-1 gap-5 mb-5">
      <SummaryCards />
      <ApplicationReceived />
    </div>
    <div class="grid lg:grid-cols-4 grid-cols-1 gap-5">
      <div class="lg:col-span-3 col-span-1">
        <EmployeePerformance />
        <div class="grid lg:grid-cols-3 col-span-1 gap-5">
          <TotalProjects />
          <UpcomingInterview />
          <RecentPayroll />
        </div>
      </div>
      <UpcomingScheduled />
    </div>
  </Vertical>
</template>

<script setup lang="ts">
import PageTitle from '~/components/PageTitle.vue'
import Vertical from '~/layouts/vertical.vue'
import HRWelcome from './components/HRWelcome.vue'
import SummaryCards from './components/SummaryCards.vue'
import ApplicationReceived from './components/ApplicationReceived.vue'
import EmployeePerformance from './components/EmployeePerformance.vue'
import TotalProjects from './components/TotalProjects.vue'
import UpcomingInterview from './components/UpcomingInterview.vue'
import RecentPayroll from './components/RecentPayroll.vue'
import UpcomingScheduled from './components/UpcomingScheduled.vue'

usePageTitle('HR')
</script>

// Nextjs-JS/src/app/(admin)/(dashboards)/hr/page.jsx
import PageBreadcrumb from '@/components/PageBreadcrumb';
import React from 'react';
import Activities from './components/Activities';
import EmployeDetails from './components/EmployeeDetails';
import ApplicationReceived from './components/ApplicationReceived';
import EmployeePerformance from './components/EmployeePerformance';
import TotalProjects from './components/TotalProjects';
import UpcomingInterview from './components/UpcomingInterview';
import BirthdayCard from './components/BirthdayCard';
import RecentPayroll from './components/RecentPayroll';
import UpcomingScheduled from './components/UpcomingScheduled';
export const metadata = {
  title: 'HR'
};
const Page = () => {
  return <main>
      <PageBreadcrumb title="HR" subtitle="Dashboard" />
      <Activities />
      <div className="grid lg:grid-cols-2 grid-cols-1 gap-5 mb-5">
        <EmployeDetails />
        <ApplicationReceived />
      </div>
      <div className="grid lg:grid-cols-4 grid-cols-1 gap-5">
        <div className="lg:col-span-3 col-span-1">
          <EmployeePerformance />
          <div className="grid lg:grid-cols-3 col-span-1 gap-5">
            <TotalProjects />
            <UpcomingInterview />
            <div className="col-span-1">
              <BirthdayCard />
              <RecentPayroll />
            </div>
          </div>
        </div>
        <div className="col-span-1">
          <UpcomingScheduled />
        </div>
      </div>
    </main>;
};
export default Page;
