// Nextjs-TS/src/app/(landing)/onepage-landing/components/Pricing.tsx
import React from 'react';
import { LuCheckCheck, LuCrown, LuGoal, LuGraduationCap, LuLuggage, LuX } from 'react-icons/lu';

type Feature = {
  name: string;
  included: boolean;
};

type PricingPlan = {
  id: number;
  title: string;
  description: string;
  price: string;
  period: string;
  icon: React.ElementType;
  iconColor: string;
  buttonText: string;
  highlight?: string;
  features: Feature[];
};

const pricingPlans: PricingPlan[] = [
  {
    id: 1,
    title: 'Lite',
    description: 'Perfect plan for Lite',
    price: '9.99',
    period: '/Monthly',
    icon: LuGoal,
    iconColor: 'text-success',
    buttonText: 'Purchase Now',
    features: [
      { name: '<b>3</b> Projects', included: true },
      { name: '<b>299 </b>Customers', included: true },
      { name: 'Scalable Bandwidth', included: true },
      { name: 'No Team Account', included: true },
      { name: 'In app messaging', included: false },
      { name: '5 FTP Login', included: false },
      { name: 'Detailed Analytics', included: false },
      { name: 'Custom Domain', included: false },
      { name: 'Smart Workflow', included: false },
      { name: 'IQ test', included: false },
    ],
  },
  {
    id: 2,
    title: 'Professional',
    description: 'For users who want to do more.',
    price: '29.99',
    period: '/Monthly',
    icon: LuGraduationCap,
    iconColor: 'text-secondary',
    buttonText: 'Purchase Now',
    features: [
      { name: '<b>3</b> Projects', included: true },
      { name: '<b>299</b> Customers', included: true },
      { name: 'Scalable Bandwidth', included: true },
      { name: '<b>3</b> No Team Account', included: true },
      { name: 'In app messaging', included: true },
      { name: '5 FTP Login', included: false },
      { name: 'Detailed Analytics', included: false },
      { name: 'Custom Domain', included: false },
      { name: 'Smart Workflow', included: false },
      { name: 'IQ test', included: false },
    ],
  },
  {
    id: 3,
    title: 'Enterprise',
    description: 'Run your company on your teams',
    price: '39.99',
    period: '/Monthly',
    icon: LuCrown,
    iconColor: 'text-primary',
    buttonText: 'Purchase Now',
    highlight: '25% Sale',
    features: [
      { name: '<b>3</b> Projects', included: true },
      { name: '<b>299</b> Customers', included: true },
      { name: 'Scalable Bandwidth', included: true },
      { name: '<b>3</b> No Team Account', included: true },
      { name: 'In app messaging', included: true },
      { name: '5 FTP Login', included: true },
      { name: 'Detailed Analytics', included: true },
      { name: 'Custom Domain', included: false },
      { name: 'Smart Workflow', included: false },
      { name: 'IQ test', included: false },
    ],
  },
  {
    id: 4,
    title: 'Unlimited',
    description: 'Your entire team in one place',
    price: '49.99',
    period: '/Monthly',
    icon: LuLuggage,
    iconColor: 'text-danger',
    buttonText: 'Purchase Now',
    features: [
      { name: '<b>3</b> Projects', included: true },
      { name: '<b>299</b> Customers', included: true },
      { name: 'Scalable Bandwidth', included: true },
      { name: '<b>3</b> No Team Account', included: true },
      { name: 'In app messaging', included: true },
      { name: '5 FTP Login', included: true },
      { name: 'Detailed Analytics', included: true },
      { name: 'Custom Domain', included: true },
      { name: 'Smart Workflow', included: true },
      { name: 'IQ test', included: true },
    ],
  },
];
const Pricing = () => {
  return (
    <section id="pricing" className="relative lg:pb-24 md:pb-18 pb-12">
      <div className="container">
        <div className="flex flex-col gap-y-16">
          <div className="text-center lg:w-3xl mx-auto">
            <h1 className="mb-4 leading-relaxed text-4xl font-semibold text-default-800">
              Tailored Website Design Package
            </h1>
            <p className="text-lg text-default-500">
              A good web design package will include designing a logo, integration with local SEO,
              linking a site to a social media presence, and more.
            </p>
          </div>

          <div className="grid lg:grid-cols-4 md:grid-cols-2 gap-5 mb-6">
            {pricingPlans.map(plan => (
              <div key={plan.id} className="card relative overflow-hidden">
                <div className="card-body">
                  {plan.highlight && (
                    <div className="size-16 absolute top-0 end-0">
                      <div className="absolute bg-primary text-center w-42.5 text-white py-1 transform rotate-45 top-6 -end-12 font-semibold">
                        {plan.highlight}
                      </div>
                    </div>
                  )}

                  <h5 className="mb-2 flex items-center gap-1.5">
                    <plan.icon className={`${plan.iconColor} size-5`} />
                    <span className="text-lg font-semibold text-default-800">{plan.title}</span>
                  </h5>

                  <p className="mb-4 text-default-500">{plan.description}</p>
                  <h1 className="mb-4 text-4xl text-default-800 font-normal">
                    <span className="text-default-400">$</span>
                    {plan.price}
                    <small className="text-base text-default-500">{plan.period}</small>
                  </h1>

                  <button
                    type="button"
                    className="btn border w-full border-dashed border-primary bg-transparent text-primary hover:bg-primary/20"
                  >
                    {plan.buttonText}
                  </button>

                  <ul className="mt-5 flex flex-col gap-3 text-sm">
                    {plan.features.map((feature, i) => (
                      <li key={i} className="flex items-center gap-2.5">
                        {feature.included ? (
                          <LuCheckCheck className="size-4 text-success" />
                        ) : (
                          <LuX className="size-4 text-danger" />
                        )}
                        {feature.included ? (
                          <span
                            className={feature.included ? 'text-default-900' : 'text-default-500'}
                            dangerouslySetInnerHTML={{ __html: feature.name }}
                          />
                        ) : (
                          <del className="text-default-500">{feature.name}</del>
                        )}
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
};

export default Pricing;

// Nuxtjs/app/pages/landing/one-page/components/Pricing.vue
<template>
  <section id="pricing" class="relative lg:pb-24 md:pb-18 pb-12">
    <div class="container">
      <div class="flex flex-col gap-y-16">
        <div class="text-center lg:w-3xl mx-auto">
          <h1 class="mb-4 leading-relaxed text-4xl font-semibold text-default-800">Tailored Website Design Package</h1>
          <p class="text-lg text-default-500">A good web design package will include designing a logo,ingratiation with local SEO, linking a site to a social media presence, and more.</p>
        </div>
        <div class="grid lg:grid-cols-4 md:grid-cols-2 gap-5 mb-6">
          <div class="card">
            <div class="card-body">
              <h5 class="mb-2 flex items-center gap-1.5">
                <Icon icon="lucide:goal" class="text-success size-5"></Icon>
                <span class="text-lg font-semibold text-default-800">Lite</span>
              </h5>
              <p class="mb-4 text-default-500">Perfect plan for Lite</p>
              <h1 class="mb-4 text-4xl text-default-800 font-normal"><span class="text-default-400">$</span>9.99<small class="text-base text-default-500">/Monthly</small></h1>
              <button type="button" class="btn border w-full border-dashed border-primary bg-transparent text-primary hover:bg-primary/20">Purchase Now</button>
              <ul class="mt-5 flex flex-col gap-3 text-sm">
                <li class="flex items-center gap-2.5">
                  <Icon icon="lucide:check-check" class="size-4 text-success"></Icon>
                  <span class="text-default-900"><b>3</b> Projects</span>
                </li>
                <li class="flex items-center gap-2.5">
                  <Icon icon="lucide:check-check" class="size-4 text-success"></Icon>
                  <span class="text-default-900"><b>299 </b>Customers</span>
                </li>
                <li class="flex items-center gap-2.5">
                  <Icon icon="lucide:check-check" class="size-4 text-success"></Icon>
                  <span class="text-default-900">Scalable Bandwidth</span>
                </li>
                <li class="flex items-center gap-2.5">
                  <Icon icon="lucide:check-check" class="size-4 text-success"></Icon>
                  <span class="text-default-900"><b>0</b>No Team Account</span>
                </li>
                <li class="flex items-center gap-2.5">
                  <Icon icon="lucide:x" class="size-4 text-danger"></Icon>
                  <del class="text-default-500">In app messaging</del>
                </li>
                <li class="flex items-center gap-2.5">
                  <Icon icon="lucide:x" class="size-4 text-danger"></Icon>
                  <del class="text-default-500">5 FTP Login</del>
                </li>
                <li class="flex items-center gap-2.5">
                  <Icon icon="lucide:x" class="size-4 text-danger"></Icon>
                  <del class="text-default-500">Detailed Analytics</del>
                </li>
                <li class="flex items-center gap-2.5">
                  <Icon icon="lucide:x" class="size-4 text-danger"></Icon>
                  <del class="text-default-500">Custom Domain</del>
                </li>
                <li class="flex items-center gap-2.5">
                  <Icon icon="lucide:x" class="size-4 text-danger"></Icon>
                  <del class="text-default-500">Smart Workflow</del>
                </li>
                <li class="flex items-center gap-2.5">
                  <Icon icon="lucide:x" class="size-4 text-danger"></Icon>
                  <del class="text-default-500">IQ test</del>
                </li>
              </ul>
            </div>
          </div>
          <div class="card">
            <div class="card-body">
              <h5 class="mb-2 flex items-center gap-1.5">
                <Icon icon="lucide:graduation-cap" class="text-secondary size-5"></Icon>
                <span class="text-lg font-semibold text-default-800">Professional</span>
              </h5>
              <p class="mb-4 text-default-500">For users who want to do more.</p>
              <h1 class="mb-4 text-4xl text-default-800 font-normal"><span class="text-default-400">$</span>29.99<small class="text-base text-default-500">/Monthly</small></h1>
              <button type="button" class="btn border w-full border-dashed border-primary bg-transparent text-primary hover:bg-primary/20">Purchase Now</button>
              <ul class="mt-5 flex flex-col gap-3 text-sm">
                <li class="flex items-center gap-2.5">
                  <Icon icon="lucide:check-check" class="size-4 text-success"></Icon>
                  <span class="text-default-900"><b>3</b> Projects</span>
                </li>
                <li class="flex items-center gap-2.5">
                  <Icon icon="lucide:check-check" class="size-4 text-success"></Icon>
                  <span class="text-default-900"><b>299</b>Customers</span>
                </li>
                <li class="flex items-center gap-2.5">
                  <Icon icon="lucide:check-check" class="size-4 text-success"></Icon>
                  <span class="text-default-900">Scalable Bandwidth</span>
                </li>
                <li class="flex items-center gap-2.5">
                  <Icon icon="lucide:check-check" class="size-4 text-success"></Icon>
                  <span class="text-default-900"><b>3</b> No Team Account</span>
                </li>
                <li class="flex items-center gap-2.5">
                  <Icon icon="lucide:check-check" class="size-4 text-success"></Icon>
                  <span class="text-default-900">In app messaging</span>
                </li>
                <li class="flex items-center gap-2.5">
                  <Icon icon="lucide:x" class="size-4 text-danger"></Icon>
                  <del class="text-default-500">5 FTP Login</del>
                </li>
                <li class="flex items-center gap-2.5">
                  <Icon icon="lucide:x" class="size-4 text-danger"></Icon>
                  <del class="text-default-500">Detailed Analytics</del>
                </li>
                <li class="flex items-center gap-2.5">
                  <Icon icon="lucide:x" class="size-4 text-danger"></Icon>
                  <del class="text-default-500">Custom Domain</del>
                </li>
                <li class="flex items-center gap-2.5">
                  <Icon icon="lucide:x" class="size-4 text-danger"></Icon>
                  <del class="text-default-500">Smart Workflow</del>
                </li>
                <li class="flex items-center gap-2.5">
                  <Icon icon="lucide:x" class="size-4 text-danger"></Icon>
                  <del class="text-default-500">IQ test</del>
                </li>
              </ul>
            </div>
          </div>
          <div class="card relative overflow-hidden">
            <div class="card-body">
              <div class="size-16 absolute top-0 end-0">
                <div class="absolute bg-primary text-center w-42.5 text-white py-1 transform rotate-45 top-6 -end-12 font-semibold">25% Sale</div>
              </div>
              <h5 class="mb-2 flex items-center gap-1.5">
                <Icon icon="lucide:crown" class="text-primary size-5"></Icon>
                <span class="text-lg font-semibold text-default-800"> Enterprise</span>
              </h5>
              <p class="mb-4 text-default-500">Run your company on your teams</p>
              <h1 class="mb-4 text-4xl text-default-800 font-normal"><span class="text-default-400">$</span>39.99<small class="text-base text-default-500">/Monthly</small></h1>
              <button type="button" class="btn border w-full border-dashed border-primary bg-transparent text-primary hover:bg-primary/20">Purchase Now</button>
              <ul class="mt-5 flex flex-col gap-3 text-sm">
                <li class="flex items-center gap-2.5">
                  <Icon icon="lucide:check-check" class="size-4 text-success"></Icon>
                  <span class="text-default-900"><b>3</b> Projects</span>
                </li>
                <li class="flex items-center gap-2.5">
                  <Icon icon="lucide:check-check" class="size-4 text-success"></Icon>
                  <span class="text-default-900"><b>299</b>Customers</span>
                </li>
                <li class="flex items-center gap-2.5">
                  <Icon icon="lucide:check-check" class="size-4 text-success"></Icon>
                  <span class="text-default-900">Scalable Bandwidth</span>
                </li>
                <li class="flex items-center gap-2.5">
                  <Icon icon="lucide:check-check" class="size-4 text-success"></Icon>
                  <span class="text-default-900"><b>3</b> No Team Account</span>
                </li>
                <li class="flex items-center gap-2.5">
                  <Icon icon="lucide:check-check" class="size-4 text-success"></Icon>
                  <span class="text-default-900">In app messaging</span>
                </li>
                <li class="flex items-center gap-2.5">
                  <Icon icon="lucide:check-check" class="size-4 text-success"></Icon>
                  <span class="text-default-900">5 FTP Login</span>
                </li>
                <li class="flex items-center gap-2.5">
                  <Icon icon="lucide:check-check" class="size-4 text-success"></Icon>
                  <span class="text-default-900">Detailed Analytics</span>
                </li>
                <li class="flex items-center gap-2.5">
                  <Icon icon="lucide:x" class="size-4 text-danger"></Icon>
                  <del class="text-default-500">Custom Domain</del>
                </li>
                <li class="flex items-center gap-2.5">
                  <Icon icon="lucide:x" class="size-4 text-danger"></Icon>
                  <del class="text-default-500">Smart Workflow</del>
                </li>
                <li class="flex items-center gap-2.5">
                  <Icon icon="lucide:x" class="size-4 text-danger"></Icon>
                  <del class="text-default-500">IQ test</del>
                </li>
              </ul>
            </div>
          </div>
          <div class="card">
            <div class="card-body">
              <h5 class="mb-2 flex items-center gap-1.5">
                <Icon icon="lucide:luggage" class="text-danger size-5"></Icon>
                <span class="text-lg font-semibold text-default-800">Unlimited</span>
              </h5>
              <p class="mb-4 text-default-500">Your entire team in one place</p>
              <h1 class="mb-4 text-4xl text-default-800 font-normal"><span class="text-default-400">$</span>49.99<small class="text-base text-default-500">/Monthly</small></h1>
              <button type="button" class="btn border w-full border-dashed border-primary bg-transparent text-primary hover:bg-primary/20">Purchase Now</button>
              <ul class="mt-5 flex flex-col gap-3 text-sm">
                <li class="flex items-center gap-2.5">
                  <Icon icon="lucide:check-check" class="size-4 text-success"></Icon>
                  <span class="text-default-900"><b>3</b> Projects</span>
                </li>
                <li class="flex items-center gap-2.5">
                  <Icon icon="lucide:check-check" class="size-4 text-success"></Icon>
                  <span class="text-default-900"><b>299</b>Customers</span>
                </li>
                <li class="flex items-center gap-2.5">
                  <Icon icon="lucide:check-check" class="size-4 text-success"></Icon>
                  <span class="text-default-900">Scalable Bandwidth</span>
                </li>
                <li class="flex items-center gap-2.5">
                  <Icon icon="lucide:check-check" class="size-4 text-success"></Icon>
                  <span class="text-default-900"><b>3</b> No Team Account</span>
                </li>
                <li class="flex items-center gap-2.5">
                  <Icon icon="lucide:check-check" class="size-4 text-success"></Icon>
                  <span class="text-default-900">In app messaging</span>
                </li>
                <li class="flex items-center gap-2.5">
                  <Icon icon="lucide:check-check" class="size-4 text-success"></Icon>
                  <span class="text-default-900">5 FTP Login</span>
                </li>
                <li class="flex items-center gap-2.5">
                  <Icon icon="lucide:check-check" class="size-4 text-success"></Icon>
                  <span class="text-default-900">Detailed Analytics</span>
                </li>
                <li class="flex items-center gap-2.5">
                  <Icon icon="lucide:check-check" class="size-4 text-success"></Icon>
                  <span class="text-default-900">Custom Domain</span>
                </li>
                <li class="flex items-center gap-2.5">
                  <Icon icon="lucide:check-check" class="size-4 text-success"></Icon>
                  <span class="text-default-900">Smart Workflow</span>
                </li>
                <li class="flex items-center gap-2.5">
                  <Icon icon="lucide:check-check" class="size-4 text-success"></Icon>
                  <span class="text-default-900">IQ test</span>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
import { Icon } from '@iconify/vue'
</script>
