// Nuxtjs/app/pages/ecommerce/order-detail/components/OrderSummary.vue
<template>
  <div class="card mt-5">
    <div class="card-body">
      <div class="flex justify-between gap-5 items-center">
        <h6 class="mb-4 card-title">Orders Summary</h6>
        <a href="#" class="text-danger text-sm underline">Cancelled Order</a>
      </div>

      <div>
        <div class="flex justify-between items-center gap-5 py-4 border-b border-dashed border-default-200">
          <div class="flex items-center gap-3">
            <div class="btn rounded-md size-12 bg-default-100">
              <img :src="img08" alt="" class="h-8" />
            </div>

            <div>
              <h6 class="mb-1 card-title">
                <a href="/ecommerce/product-detail" class="transition-all duration-300 ease-linear hover:text-primary">Roar Twill Blue Baseball Cap</a>
              </h6>
              <p class="text-default-500 text-sm">$149.99 x 02</p>
            </div>
          </div>
          <span class="text-sm">$299.98</span>
        </div>

        <div class="flex justify-between items-center gap-5 py-4 border-b border-dashed border-default-200">
          <div class="flex items-center gap-3">
            <div class="btn rounded-md size-12 bg-default-100">
              <img :src="img04" alt="" class="h-8" />
            </div>

            <div>
              <h6 class="mb-1 card-title"><a href="/ecommerce/product-detail" class="transition-all duration-300 ease-linear hover:text-primary">Mesh Ergonomic Green Chair</a></h6>
              <p class="text-default-500 text-sm">$362.21 x 1</p>
            </div>
          </div>
          <span class="text-sm">$362.21</span>
        </div>

        <div class="flex justify-between items-center gap-5 py-4 border-b border-dashed border-default-200">
          <div class="flex items-center gap-3">
            <div class="btn rounded-md size-12 bg-default-100">
              <img :src="img01" alt="" class="h-8" />
            </div>

            <div>
              <h6 class="mb-1 card-title"><a href="/ecommerce/product-detail" class="transition-all duration-300 ease-linear hover:text-primary">Smartest Printed T-shirt</a></h6>
              <p class="text-default-500 text-sm">$89.99 x 03</p>
            </div>
          </div>
          <span class="text-sm">$269.97</span>
        </div>

        <div class="flex justify-between items-center gap-5 py-3 text-sm">
          <span class="text-default-500">Sub Total </span>
          <span class="text-default-800">$932.16</span>
        </div>

        <div class="flex justify-between items-center gap-5 py-3 text-sm">
          <span class="text-default-500">Estimated Tax (18%) </span>
          <span class="text-default-800">$167.79</span>
        </div>

        <div class="flex justify-between items-center gap-5 py-3 text-sm">
          <span class="text-default-500">Item Discounts (12%)</span>
          <span class="text-default-800">-$111.86</span>
        </div>

        <div class="flex justify-between items-center gap-5 py-3 text-sm">
          <span class="text-default-500">Shipping Charge </span>
          <span class="text-default-800">$0</span>
        </div>

        <div class="flex justify-between items-center gap-5 pt-4 font-semibold text-sm">
          <span class="text-default-500">Total Amount (USD) </span>
          <span class="text-default-800">$988.09</span>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import img01 from '~/assets/images/product/img-01.png'
import img04 from '~/assets/images/product/img-04.png'
import img08 from '~/assets/images/product/img-08.png'
</script>

// Nextjs-JS/src/app/(admin)/(app)/(ecommerce)/cart/components/OrderSummary.jsx
import React from 'react';
import { LuContainer, LuTruck } from 'react-icons/lu';
const OrderSummary = () => {
  return <div className="col-span-1">
      <div className="sticky top-20">
        <div className="p-5 card mb-5">
          <h6 className="card-title mb-4">Order Summary</h6>
          <div className="overflow-x-auto">
            <table className="w-full">
              <tbody className="table-total">
                <tr className="text-sm">
                  <td className="py-2 text-default-500"> Sub Total </td>
                  <td className="py-2 text-default-500 cart-subtotal"> $932.16 </td>
                </tr>

                <tr className="text-sm">
                  <td className="py-2 text-default-500"> Estimated Tax (18%)</td>
                  <td className="py-2 text-default-500 cart-tax"> $167.79</td>
                </tr>

                <tr className="text-sm">
                  <td className="py-2 text-default-500">Item Discounts (12%) </td>
                  <td className="py-2 text-default-500 cart-discount"> -$111.86 </td>
                </tr>

                <tr className="text-sm">
                  <td className="py-2 text-default-500"> Shipping Charge </td>
                  <td className="py-2 text-default-500 cart-shipping"> $0 </td>
                </tr>

                <tr className="font-semibold text-sm text-default-800">
                  <td className="pt-2"> Total Amount (USD) </td>
                  <td className="pt-2 cart-total"> $988.09 </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>

        <div className="grid grid-cols-2 gap-2 mb-5">
          <button type="button" className="btn bg-danger/90 text-white transition-all duration-300 hover:bg-danger">
            Continue to Shopping
          </button>

          <button type="button" className="btn bg-primary/90 text-white transition-all duration-300 hover:bg-primary">
            Checkout
          </button>
        </div>

        <div className="p-5 card mb-5">
          <div className="flex items-center gap-5">
            <div className="btn bg-default-200 size-12">
              <LuTruck className="size-6 text-default-500 fill-default-200" />
            </div>

            <div>
              <h6 className="mb-1 text-default-800 font-semibold text-sm">Estimated Delivery</h6>
              <p className="text-default-500 text-sm">01 - 07 Dec, 2023</p>
            </div>
          </div>
        </div>

        <div className="p-5 card">
          <div className="flex items-center gap-5">
            <div className="btn bg-default-200 size-12">
              <LuContainer className="size-6 text-default-500 fill-default-200" />
            </div>

            <div>
              <h6 className="mb-1 text-default-800 font-semibold text-sm">
                Free Shipping & Returns
              </h6>
              <p className="text-default-500 text-sm">On all orders over $200.00</p>
            </div>
          </div>
        </div>
      </div>
    </div>;
};
export default OrderSummary;
