// Nuxtjs/app/pages/dashboard/email/components/EmailMarketing.vue
<template>
  <div class="col-span-1">
    <div class="card">
      <div class="card-header">
        <h6 class="card-title">Email Marketing</h6>
        <div class="hs-dropdown relative inline-flex">
          <button type="button" class="hs-dropdown-toggle btn size-7.5 hover:bg-default-150" aria-haspopup="menu" aria-expanded="false" aria-label="Dropdown" hs-dropdown-placement="bottom-end">
            <Icon icon="lucide:ellipsis" class="iconify size-4 text-default-600"></Icon>
          </button>
          <div class="hs-dropdown-menu" role="menu" aria-orientation="vertical" aria-labelledby="hs-dropdown-custom-icon-trigger">
            <a class="flex items-center gap-x-3.5 py-1.5 font-medium px-3 text-default-600 hover:bg-default-150 rounded" href="#"> This Year </a>
            <a class="flex items-center gap-x-3.5 py-1.5 font-medium px-3 text-default-600 hover:bg-default-150 rounded" href="#"> Last Year </a>
          </div>
        </div>
      </div>
      <div class="card-body">
        <client-only>
          <VueApexCharts type="radialBar" height="370" :options="emailMarketingChartOptions" :series="emailMarketingChartseries" />
        </client-only>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import VueApexCharts from 'vue3-apexcharts'
import { emailMarketingChartOptions, emailMarketingChartseries } from './data'
</script>

// Nextjs-JS/src/app/(admin)/(dashboards)/email/components/EmailMarketing.jsx
'use client';

import ApexChartClient from '@/components/client-wrapper/ApexChartClient';
import Link from 'next/link';
import React from 'react';
import { getEmailMarketingChart } from './data';
import { LuEllipsis } from 'react-icons/lu';
const EmailMarketing = () => {
  return <div className="col-span-1">
      <div className="card">
        <div className="card-header">
          <h6 className="card-title">Email Marketing</h6>
          <div className="hs-dropdown relative inline-flex">
            <button type="button" className="hs-dropdown-toggle btn size-7.5 hover:bg-default-150" aria-haspopup="menu" aria-expanded="false" aria-label="Dropdown" hs-dropdown-placement="bottom-end">
              <LuEllipsis className="size-4 text-default-600" />
            </button>

            <div className="hs-dropdown-menu" role="menu" aria-orientation="vertical" aria-labelledby="hs-dropdown-custom-icon-trigger">
              <Link className="flex items-center gap-x-3.5 py-1.5 font-medium px-3 text-default-600 hover:bg-default-150 rounded" href="#">
                This Year
              </Link>

              <Link className="flex items-center gap-x-3.5 py-1.5 font-medium px-3 text-default-600 hover:bg-default-150 rounded" href="#">
                Last Year
              </Link>
            </div>
          </div>
        </div>

        <div className="card-body">
          <ApexChartClient getOptions={getEmailMarketingChart} series={getEmailMarketingChart().series} type="radialBar" height={345} />
        </div>
      </div>
    </div>;
};
export default EmailMarketing;
