// Vuejs/src/layouts/components/sidenav/components/AppMenu.vue
<template>
  <ul class="side-nav p-3 hs-accordion-group">
    <template v-for="(item, idx) in menuItems" :key="item.key || idx">
      <li v-if="item.isTitle" class="menu-title">
        <span>{{ item.label }}</span>
      </li>
      <template v-else>
        <MenuItemWithChildren v-if="item.children" :item="item" :open-menu-key="openMenuKey" :set-open-menu-key="setOpenMenuKey" />
        <MenuItem v-else :item="item" :key="idx" />
      </template>
    </template>
  </ul>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { menuItems } from './data'
import MenuItem from './MenuItem.vue'
import MenuItemWithChildren from './MenuItemWithChildren.vue'

const openMenuKey = ref<string | null>(null)

const setOpenMenuKey = (key: string | null) => {
  openMenuKey.value = key
}
</script>

// React-TS/src/components/layouts/SideNav/AppMenu.tsx
import { Link, useLocation } from 'react-router-dom';
import { LuChevronRight } from 'react-icons/lu';
import { menuItemsData, type MenuItemType } from './menu';

const isItemActive = (item: MenuItemType, pathname: string): boolean => {
  if (item.href && pathname === item.href) return true;
  if (item.children) {
    return item.children.some(child => isItemActive(child, pathname));
  }
  return false;
};

const MenuItemWithChildren = ({ item }: { item: MenuItemType }) => {
  const { pathname } = useLocation();
  const Icon = item.icon;

  const isActive = isItemActive(item, pathname);

  return (
    <li className={`menu-item hs-accordion ${isActive ? 'active' : ''}`}>
      <button
        className={`hs-accordion-toggle menu-link ${isActive ? 'active' : ''}`}
      >
        {Icon && (
          <span className="menu-icon">
            <Icon />
          </span>
        )}
        <span className="menu-text">{item.label}</span>
        <span className="menu-arrow">
          <LuChevronRight />
        </span>
      </button>

      <ul
        className={`sub-menu hs-accordion-content hs-accordion-group ${
          isActive ? 'block' : 'hidden'
        }`}
      >
        {item.children?.map((child: MenuItemType) =>
          child.children ? (
            <MenuItemWithChildren key={child.key} item={child} />
          ) : (
            <MenuItem key={child.key} item={child} />
          )
        )}
      </ul>
    </li>
  );
};

const MenuItem = ({ item }: { item: MenuItemType }) => {
  const { pathname } = useLocation();
  const Icon = item.icon;
  const isActive = pathname === item.href;

  return (
    <li className={`menu-item ${isActive ? 'active' : ''}`}>
      <Link to={item.href ?? '#'} className={`menu-link ${isActive ? 'active' : ''}`}>
        {Icon && (
          <span className="menu-icon">
            <Icon />
          </span>
        )}
        <div className="menu-text">{item.label}</div>
      </Link>
    </li>
  );
};

const AppMenu = () => {
  return (
    <ul className="side-nav p-3 hs-accordion-group">
      {menuItemsData.map((item: MenuItemType) =>
        item.isTitle ? (
          <li className="menu-title" key={item.key}>
            <span>{item.label}</span>
          </li>
        ) : item.children ? (
          <MenuItemWithChildren key={item.key} item={item} />
        ) : (
          <MenuItem key={item.key} item={item} />
        )
      )}
    </ul>
  );
};

export default AppMenu;
