// Nextjs-JS/src/app/(admin)/(pages)/pricing/page.jsx
import PageBreadcrumb from '@/components/PageBreadcrumb';
import React from 'react';
import Pricing from './components/PricingCard';
import HorizontalPricing from './components/HorizontalPricing';
export const metadata = {
  title: 'Pricing'
};
const Page = () => {
  return <main>
      <PageBreadcrumb title="Pricing" subtitle="Pages" />
      <Pricing />
      <HorizontalPricing />
    </main>;
};
export default Page;

// Nuxtjs/app/pages/(pages)/pricing/index.vue
<template>
  <Vertical>
    <PageTitle subtitle="Pages" title="Pricing" />
    <Pricing />
    <h5 class="mt-2 mb-4 underline text-lg font-semibold text-default-700">Horizontal Pricing</h5>
    <HorizontalPricing />
  </Vertical>
</template>

<script setup lang="ts">
import PageTitle from '~/components/PageTitle.vue'
import Vertical from '~/layouts/vertical.vue'
import Pricing from './components/Pricing.vue'
import HorizontalPricing from './components/HorizontalPricing.vue'

usePageTitle('Pricing')
</script>
