// Nuxtjs/app/pages/hr-management/(attendance)/attendance/index.vue
<template>
  <Vertical>
    <PageTitle subtitle="Menu" title="Attendance" />
    <div class="grid lg:grid-cols-4 grid-cols-1 gap-5">
      <Profile />
      <Table />
    </div>
  </Vertical>
</template>

<script setup lang="ts">
import PageTitle from '~/components/PageTitle.vue'
import Vertical from '~/layouts/vertical.vue'
import Profile from './components/Profile.vue'
import Table from './components/Table.vue'

usePageTitle('Attendance')
</script>

// Nextjs-JS/src/app/(admin)/(app)/(hr)/attendance/page.jsx
import PageBreadcrumb from '@/components/PageBreadcrumb';
import React from 'react';
import EmployeeDetails from './components/EmployeeDetails';
import EmployeeWorkDetails from './components/EmployeeWorkDetails';
import EmployeeWork from './components/EmployeeWork';
export const metadata = {
  title: 'Attendance'
};
const Page = () => {
  return <main>
      <PageBreadcrumb title="Attendance" subtitle="Menu" />
      <div className="grid lg:grid-cols-4 grid-cols-1 gap-5">
        <EmployeeDetails />
        <div className="lg:col-span-3 col-span-1">
          <EmployeeWorkDetails />
          <EmployeeWork />
        </div>
      </div>
    </main>;
};
export default Page;
