// Nuxtjs/app/pages/ecommerce/checkout/components/ShoppingInformation.vue
<template>
  <div class="p-5 card mb-5">
    <h6 class="card-title mb-4">Shipping Information</h6>

    <div class="grid lg:grid-cols-3 md:grid-cols-2 grid-cols-1 gap-5 mb-5">
      <div class="col-span-1">
        <label for="firstNameInput" class="inline-block mb-2 text-sm text-default-800 font-medium">First Name</label>
        <input type="text" id="firstNameInput" class="form-input" placeholder="Enter First Name" style="border: 1px solid oklch(92% 0.004 286.32)" />
      </div>

      <div class="col-span-1">
        <label for="middleNameInput" class="inline-block mb-2 text-sm text-default-800 font-medium">Middle Name</label>
        <input type="text" id="middleNameInput" class="form-input" placeholder="Enter Middle Name" style="border: 1px solid oklch(92% 0.004 286.32)" />
      </div>

      <div class="col-span-1">
        <label for="lastNameInput" class="inline-block mb-2 text-sm text-default-800 font-medium">Last Name</label>
        <input type="text" id="lastNameInput" class="form-input" placeholder="Enter Last Name" style="border: 1px solid oklch(92% 0.004 286.32)" />
      </div>

      <div class="col-span-1">
        <label for="phoneNumberInput" class="inline-block mb-2 text-sm text-default-800 font-medium">Phone Number</label>
        <input type="text" id="phoneNumberInput" class="form-input" placeholder="(012) 345 678 9010" style="border: 1px solid oklch(92% 0.004 286.32)" />
      </div>

      <div class="col-span-1">
        <label for="alternativeNumberInput" class="inline-block mb-2 text-sm text-default-800 font-medium">Alternative Number</label>
        <input type="text" id="alternativeNumberInput" class="form-input" placeholder="(012) 345 678 9010" style="border: 1px solid oklch(92% 0.004 286.32)" />
      </div>

      <div class="col-span-1">
        <label for="emailAddressInput" class="inline-block mb-2 text-sm text-default-800 font-medium">Email Address</label>
        <input type="email" id="emailAddressInput" class="form-input" placeholder="Enter email" style="border: 1px solid oklch(92% 0.004 286.32)" />
      </div>
    </div>

    <div class="mb-5">
      <label for="streetAddressInput" class="inline-block mb-2 text-sm text-default-800 font-medium">Street Address</label>
      <input type="text" id="streetAddressInput" class="form-input" placeholder="Street address" style="border: 1px solid oklch(92% 0.004 286.32)" />
    </div>

    <div class="mb-5">
      <label for="townCityInput" class="inline-block mb-2 text-sm text-default-800 font-medium">Town/City</label>
      <input type="text" id="townCityInput" class="form-input" placeholder="Town/City" style="border: 1px solid oklch(92% 0.004 286.32)" />
    </div>

    <div class="grid lg:grid-cols-3 grid-cols-1 gap-5">
      <div class="col-span-1">
        <label for="stateInput" class="inline-block mb-2 text-sm text-default-800 font-medium">State</label>
        <input type="text" id="stateInput" class="form-input" placeholder="State" style="border: 1px solid oklch(92% 0.004 286.32)" />
      </div>

      <div class="col-span-1">
        <label for="stateInput" class="inline-block mb-2 text-sm text-default-800 font-medium">Country</label>
        <select style="border: 1px solid oklch(92% 0.004 286.32)" class="form-input">
          <option value="Afghanistan">Afghanistan</option>
          <option value="Åland Islands">Åland Islands</option>
          <option value="Albania">Albania</option>
          <option value="Algeria">Algeria</option>
          <option value="American Samoa">American Samoa</option>
          <option value="Andorra">Andorra</option>
          <option value="Angola">Angola</option>
          <option value="Anguilla">Anguilla</option>
          <option value="Antarctica">Antarctica</option>
          <option value="Antigua and Barbuda">Antigua and Barbuda</option>
          <option value="Argentina">Argentina</option>
          <option value="Armenia">Armenia</option>
          <option value="Aruba">Aruba</option>
          <option value="Australia">Australia</option>
          <option value="Austria">Austria</option>
          <option value="Azerbaijan">Azerbaijan</option>
          <option value="Bahamas">Bahamas</option>
          <option value="Bahrain">Bahrain</option>
          <option value="Bangladesh">Bangladesh</option>
          <option value="Barbados">Barbados</option>
          <option value="Belarus">Belarus</option>
          <option value="Belgium">Belgium</option>
          <option value="Belize">Belize</option>
          <option value="Benin">Benin</option>
          <option value="Bermuda">Bermuda</option>
          <option value="Bhutan">Bhutan</option>
          <option value="Bolivia">Bolivia</option>
          <option value="Bosnia and Herzegovina">Bosnia and Herzegovina</option>
          <option value="Botswana">Botswana</option>
          <option value="Bouvet Island">Bouvet Island</option>
          <option value="Brazil">Brazil</option>
          <option value="British Indian Ocean Territory">British Indian Ocean Territory</option>
          <option value="Brunei Darussalam">Brunei Darussalam</option>
          <option value="Bulgaria">Bulgaria</option>
          <option value="Burkina Faso">Burkina Faso</option>
          <option value="Burundi">Burundi</option>
          <option value="Cambodia">Cambodia</option>
          <option value="Cameroon">Cameroon</option>
          <option value="Canada">Canada</option>
          <option value="Cape Verde">Cape Verde</option>
          <option value="Cayman Islands">Cayman Islands</option>
          <option value="Central African Republic">Central African Republic</option>
          <option value="Chad">Chad</option>
          <option value="Chile">Chile</option>
          <option value="China">China</option>
          <option value="Christmas Island">Christmas Island</option>
          <option value="Cocos (Keeling) Islands">Cocos (Keeling) Islands</option>
          <option value="Colombia">Colombia</option>
          <option value="Comoros">Comoros</option>
          <option value="Congo">Congo</option>
          <option value="Congo, The Democratic Republic of The">Congo, The Democratic Republic of The</option>
          <option value="Cook Islands">Cook Islands</option>
          <option value="Costa Rica">Costa Rica</option>
          <option value="Cote D'ivoire">Cote D'ivoire</option>
          <option value="Croatia">Croatia</option>
          <option value="Cuba">Cuba</option>
          <option value="Cyprus">Cyprus</option>
          <option value="Czech Republic">Czech Republic</option>
          <option value="Denmark">Denmark</option>
          <option value="Djibouti">Djibouti</option>
          <option value="Dominica">Dominica</option>
          <option value="Dominican Republic">Dominican Republic</option>
          <option value="Ecuador">Ecuador</option>
          <option value="Egypt">Egypt</option>
          <option value="El Salvador">El Salvador</option>
          <option value="Equatorial Guinea">Equatorial Guinea</option>
          <option value="Eritrea">Eritrea</option>
          <option value="Estonia">Estonia</option>
          <option value="Ethiopia">Ethiopia</option>
          <option value="Falkland Islands (Malvinas)">Falkland Islands (Malvinas)</option>
          <option value="Faroe Islands">Faroe Islands</option>
          <option value="Fiji">Fiji</option>
          <option value="Finland">Finland</option>
          <option value="France">France</option>
          <option value="French Guiana">French Guiana</option>
          <option value="French Polynesia">French Polynesia</option>
          <option value="French Southern Territories">French Southern Territories</option>
          <option value="Gabon">Gabon</option>
          <option value="Gambia">Gambia</option>
          <option value="Georgia">Georgia</option>
          <option value="Germany">Germany</option>
          <option value="Ghana">Ghana</option>
          <option value="Gibraltar">Gibraltar</option>
          <option value="Greece">Greece</option>
          <option value="Greenland">Greenland</option>
          <option value="Grenada">Grenada</option>
          <option value="Guadeloupe">Guadeloupe</option>
          <option value="Guam">Guam</option>
          <option value="Guatemala">Guatemala</option>
          <option value="Guernsey">Guernsey</option>
          <option value="Guinea">Guinea</option>
          <option value="Guinea-bissau">Guinea-bissau</option>
          <option value="Guyana">Guyana</option>
          <option value="Haiti">Haiti</option>
          <option value="Heard Island and Mcdonald Islands">Heard Island and Mcdonald Islands</option>
          <option value="Holy See (Vatican City State)">Holy See (Vatican City State)</option>
          <option value="Honduras">Honduras</option>
          <option value="Hong Kong">Hong Kong</option>
          <option value="Hungary">Hungary</option>
          <option value="Iceland">Iceland</option>
          <option value="India">India</option>
          <option value="Indonesia">Indonesia</option>
          <option value="Iran, Islamic Republic of">Iran, Islamic Republic of</option>
          <option value="Iraq">Iraq</option>
          <option value="Ireland">Ireland</option>
          <option value="Isle of Man">Isle of Man</option>
          <option value="Israel">Israel</option>
          <option value="Italy">Italy</option>
          <option value="Jamaica">Jamaica</option>
          <option value="Japan">Japan</option>
          <option value="Jersey">Jersey</option>
          <option value="Jordan">Jordan</option>
          <option value="Kazakhstan">Kazakhstan</option>
          <option value="Kenya">Kenya</option>
          <option value="Kiribati">Kiribati</option>
          <option value="Korea, Democratic People's Republic of">Korea, Democratic People's Republic of</option>
          <option value="Korea, Republic of">Korea, Republic of</option>
          <option value="Kuwait">Kuwait</option>
          <option value="Kyrgyzstan">Kyrgyzstan</option>
          <option value="Lao People's Democratic Republic">Lao People's Democratic Republic</option>
          <option value="Latvia">Latvia</option>
          <option value="Lebanon">Lebanon</option>
          <option value="Lesotho">Lesotho</option>
          <option value="Liberia">Liberia</option>
          <option value="Libyan Arab Jamahiriya">Libyan Arab Jamahiriya</option>
          <option value="Liechtenstein">Liechtenstein</option>
          <option value="Lithuania">Lithuania</option>
          <option value="Luxembourg">Luxembourg</option>
          <option value="Macao">Macao</option>
          <option value="Macedonia, The Former Yugoslav Republic of">Macedonia, The Former Yugoslav Republic of</option>
          <option value="Madagascar">Madagascar</option>
          <option value="Malawi">Malawi</option>
          <option value="Malaysia">Malaysia</option>
          <option value="Maldives">Maldives</option>
          <option value="Mali">Mali</option>
          <option value="Malta">Malta</option>
          <option value="Marshall Islands">Marshall Islands</option>
          <option value="Martinique">Martinique</option>
          <option value="Mauritania">Mauritania</option>
          <option value="Mauritius">Mauritius</option>
          <option value="Mayotte">Mayotte</option>
          <option value="Mexico">Mexico</option>
          <option value="Micronesia, Federated States of">Micronesia, Federated States of</option>
          <option value="Moldova, Republic of">Moldova, Republic of</option>
          <option value="Monaco">Monaco</option>
          <option value="Mongolia">Mongolia</option>
          <option value="Montenegro">Montenegro</option>
          <option value="Montserrat">Montserrat</option>
          <option value="Morocco">Morocco</option>
          <option value="Mozambique">Mozambique</option>
          <option value="Myanmar">Myanmar</option>
          <option value="Namibia">Namibia</option>
          <option value="Nauru">Nauru</option>
          <option value="Nepal">Nepal</option>
          <option value="Netherlands">Netherlands</option>
          <option value="Netherlands Antilles">Netherlands Antilles</option>
          <option value="New Caledonia">New Caledonia</option>
          <option value="New Zealand">New Zealand</option>
          <option value="Nicaragua">Nicaragua</option>
          <option value="Niger">Niger</option>
          <option value="Nigeria">Nigeria</option>
          <option value="Niue">Niue</option>
          <option value="Norfolk Island">Norfolk Island</option>
          <option value="Northern Mariana Islands">Northern Mariana Islands</option>
          <option value="Norway">Norway</option>
          <option value="Oman">Oman</option>
          <option value="Pakistan">Pakistan</option>
          <option value="Palau">Palau</option>
          <option value="Palestinian Territory, Occupied">Palestinian Territory, Occupied</option>
          <option value="Panama">Panama</option>
          <option value="Papua New Guinea">Papua New Guinea</option>
          <option value="Paraguay">Paraguay</option>
          <option value="Peru">Peru</option>
          <option value="Philippines">Philippines</option>
          <option value="Pitcairn">Pitcairn</option>
          <option value="Poland">Poland</option>
          <option value="Portugal">Portugal</option>
          <option value="Puerto Rico">Puerto Rico</option>
          <option value="Qatar">Qatar</option>
          <option value="Reunion">Reunion</option>
          <option value="Romania">Romania</option>
          <option value="Russian Federation">Russian Federation</option>
          <option value="Rwanda">Rwanda</option>
          <option value="Saint Helena">Saint Helena</option>
          <option value="Saint Kitts and Nevis">Saint Kitts and Nevis</option>
          <option value="Saint Lucia">Saint Lucia</option>
          <option value="Saint Pierre and Miquelon">Saint Pierre and Miquelon</option>
          <option value="Saint Vincent and The Grenadines">Saint Vincent and The Grenadines</option>
          <option value="Samoa">Samoa</option>
          <option value="San Marino">San Marino</option>
          <option value="Sao Tome and Principe">Sao Tome and Principe</option>
          <option value="Saudi Arabia">Saudi Arabia</option>
          <option value="Senegal">Senegal</option>
          <option value="Serbia">Serbia</option>
          <option value="Seychelles">Seychelles</option>
          <option value="Sierra Leone">Sierra Leone</option>
          <option value="Singapore">Singapore</option>
          <option value="Slovakia">Slovakia</option>
          <option value="Slovenia">Slovenia</option>
          <option value="Solomon Islands">Solomon Islands</option>
          <option value="Somalia">Somalia</option>
          <option value="South Africa">South Africa</option>
          <option value="South Georgia and The South Sandwich Islands">South Georgia and The South Sandwich Islands</option>
          <option value="Spain">Spain</option>
          <option value="Sri Lanka">Sri Lanka</option>
          <option value="Sudan">Sudan</option>
          <option value="Suriname">Suriname</option>
          <option value="Svalbard and Jan Mayen">Svalbard and Jan Mayen</option>
          <option value="Swaziland">Swaziland</option>
          <option value="Sweden">Sweden</option>
          <option value="Switzerland">Switzerland</option>
          <option value="Syrian Arab Republic">Syrian Arab Republic</option>
          <option value="Taiwan">Taiwan</option>
          <option value="Tajikistan">Tajikistan</option>
          <option value="Tanzania, United Republic of">Tanzania, United Republic of</option>
          <option value="Thailand">Thailand</option>
          <option value="Timor-leste">Timor-leste</option>
          <option value="Togo">Togo</option>
          <option value="Tokelau">Tokelau</option>
          <option value="Tonga">Tonga</option>
          <option value="Trinidad and Tobago">Trinidad and Tobago</option>
          <option value="Tunisia">Tunisia</option>
          <option value="Turkey">Turkey</option>
          <option value="Turkmenistan">Turkmenistan</option>
          <option value="Turks and Caicos Islands">Turks and Caicos Islands</option>
          <option value="Tuvalu">Tuvalu</option>
          <option value="Uganda">Uganda</option>
          <option value="Ukraine">Ukraine</option>
          <option value="United Arab Emirates">United Arab Emirates</option>
          <option value="United Kingdom">United Kingdom</option>
          <option value="United States">United States</option>
          <option value="United States Minor Outlying Islands">United States Minor Outlying Islands</option>
          <option value="Uruguay">Uruguay</option>
          <option value="Uzbekistan">Uzbekistan</option>
          <option value="Vanuatu">Vanuatu</option>
          <option value="Venezuela">Venezuela</option>
          <option value="Viet Nam">Viet Nam</option>
          <option value="Virgin Islands, British">Virgin Islands, British</option>
          <option value="Virgin Islands, U.S.">Virgin Islands, U.S.</option>
          <option value="Wallis and Futuna">Wallis and Futuna</option>
          <option value="Western Sahara">Western Sahara</option>
          <option value="Yemen">Yemen</option>
          <option value="Zambia">Zambia</option>
          <option value="Zimbabwe">Zimbabwe</option>
        </select>
      </div>

      <div class="col-span-1">
        <label for="zipcodeInput" class="inline-block mb-2 text-sm text-default-800 font-medium">ZipCode</label>
        <input type="text" id="zipcodeInput" class="form-input" placeholder="ZipCode" style="border: 1px solid oklch(92% 0.004 286.32)" />
      </div>
    </div>
  </div>
</template>

<script setup lang="ts"></script>

// React-JS/src/app/(admin)/(app)/(ecommerce)/checkout/components/ShoppingInformation.jsx
import delivery01 from '@/assets/images/brand/delivery-1.png';
import delivery02 from '@/assets/images/brand/delivery-2.png';
import delivery03 from '@/assets/images/brand/delivery-3.png';
import payment01 from '@/assets/images/payment/img-01.png';
import payment02 from '@/assets/images/payment/img-02.png';
import payment03 from '@/assets/images/payment/img-03.png';
import payment04 from '@/assets/images/payment/img-04.png';
import { LuChevronLeft, LuMoveRight } from 'react-icons/lu';
import { Link } from 'react-router';
const ShoppingInformation = () => {
  return <div className="lg:col-span-2 col-span-1">
      <div className="flex justify-between gap-5 mb-5 items-center">
        <Link to="#" className="flex gap-1.25 text-sm items-center text-primary">
          <LuChevronLeft className="size-4" />
          Back to Cart
        </Link>

        <button type="button" className="text-[13px] py-2 px-4 rounded bg-primary text-white transition-all duration-300 hover:bg-blue-600 inline-flex items-center">
          Place Order
          <LuMoveRight className="size-4 ms-1" />
        </button>
      </div>

      <div className="p-5 card mb-5">
        <h6 className="card-title mb-4">Shipping Information</h6>

        <div className="grid lg:grid-cols-3 md:grid-cols-2 grid-cols-1 gap-5 mb-5">
          <div className="col-span-1">
            <label htmlFor="firstNameInput" className="inline-block mb-2 text-sm text-default-800 font-medium">
              First Name
            </label>
            <input type="text" id="firstNameInput" className="form-input" placeholder="Enter First Name" />
          </div>

          <div className="col-span-1">
            <label htmlFor="middleNameInput" className="inline-block mb-2 text-sm text-default-800 font-medium">
              Middle Name
            </label>
            <input type="text" id="middleNameInput" className="form-input" placeholder="Enter Middle Name" />
          </div>

          <div className="col-span-1">
            <label htmlFor="lastNameInput" className="inline-block mb-2 text-sm text-default-800 font-medium">
              Last Name
            </label>
            <input type="text" id="lastNameInput" className="form-input" placeholder="Enter Last Name" />
          </div>

          <div className="col-span-1">
            <label htmlFor="phoneNumberInput" className="inline-block mb-2 text-sm text-default-800 font-medium">
              Phone Number
            </label>
            <input type="text" id="phoneNumberInput" className="form-input" placeholder="(012) 345 678 9010" />
          </div>

          <div className="col-span-1">
            <label htmlFor="alternativeNumberInput" className="inline-block mb-2 text-sm text-default-800 font-medium">
              Alternative Number
            </label>
            <input type="text" id="alternativeNumberInput" className="form-input" placeholder="(012) 345 678 9010" />
          </div>

          <div className="col-span-1">
            <label htmlFor="emailAddressInput" className="inline-block mb-2 text-sm text-default-800 font-medium">
              Email Address
            </label>
            <input type="email" id="emailAddressInput" className="form-input" placeholder="Enter email" />
          </div>
        </div>

        <div className="mb-5">
          <label htmlFor="streetAddressInput" className="inline-block mb-2 text-sm text-default-800 font-medium">
            Street Address
          </label>
          <input type="text" id="streetAddressInput" className="form-input" placeholder="Street address" />
        </div>

        <div className="mb-5">
          <label htmlFor="townCityInput" className="inline-block mb-2 text-sm text-default-800 font-medium">
            Town/City
          </label>
          <input type="text" id="townCityInput" className="form-input" placeholder="Town/City" />
        </div>

        <div className="grid lg:grid-cols-3 grid-cols-1 gap-5">
          <div className="col-span-1">
            <label htmlFor="stateInput" className="inline-block mb-2 text-sm text-default-800 font-medium">
              State
            </label>
            <input type="text" id="stateInput" className="form-input" placeholder="State" />
          </div>

          <div className="col-span-1">
            <label htmlFor="stateInput" className="inline-block mb-2 text-sm text-default-800 font-medium">
              Country
            </label>
            <select className="form-input">
              <option value="Afghanistan">Afghanistan</option>
              <option value="Åland Islands">Åland Islands</option>
              <option value="Albania">Albania</option>
              <option value="Algeria">Algeria</option>
              <option value="American Samoa">American Samoa</option>
              <option value="Andorra">Andorra</option>
              <option value="Angola">Angola</option>
              <option value="Anguilla">Anguilla</option>
              <option value="Antarctica">Antarctica</option>
              <option value="Antigua and Barbuda">Antigua and Barbuda</option>
              <option value="Argentina">Argentina</option>
              <option value="Armenia">Armenia</option>
              <option value="Aruba">Aruba</option>
              <option value="Australia">Australia</option>
              <option value="Austria">Austria</option>
              <option value="Azerbaijan">Azerbaijan</option>
              <option value="Bahamas">Bahamas</option>
              <option value="Bahrain">Bahrain</option>
              <option value="Bangladesh">Bangladesh</option>
              <option value="Barbados">Barbados</option>
              <option value="Belarus">Belarus</option>
              <option value="Belgium">Belgium</option>
              <option value="Belize">Belize</option>
              <option value="Benin">Benin</option>
              <option value="Bermuda">Bermuda</option>
              <option value="Bhutan">Bhutan</option>
              <option value="Bolivia">Bolivia</option>
              <option value="Bosnia and Herzegovina">Bosnia and Herzegovina</option>
              <option value="Botswana">Botswana</option>
              <option value="Bouvet Island">Bouvet Island</option>
              <option value="Brazil">Brazil</option>
              <option value="British Indian Ocean Territory">British Indian Ocean Territory</option>
              <option value="Brunei Darussalam">Brunei Darussalam</option>
              <option value="Bulgaria">Bulgaria</option>
              <option value="Burkina Faso">Burkina Faso</option>
              <option value="Burundi">Burundi</option>
              <option value="Cambodia">Cambodia</option>
              <option value="Cameroon">Cameroon</option>
              <option value="Canada">Canada</option>
              <option value="Cape Verde">Cape Verde</option>
              <option value="Cayman Islands">Cayman Islands</option>
              <option value="Central African Republic">Central African Republic</option>
              <option value="Chad">Chad</option>
              <option value="Chile">Chile</option>
              <option value="China">China</option>
              <option value="Christmas Island">Christmas Island</option>
              <option value="Cocos (Keeling) Islands">Cocos (Keeling) Islands</option>
              <option value="Colombia">Colombia</option>
              <option value="Comoros">Comoros</option>
              <option value="Congo">Congo</option>
              <option value="Congo, The Democratic Republic of The">
                Congo, The Democratic Republic of The
              </option>
              <option value="Cook Islands">Cook Islands</option>
              <option value="Costa Rica">Costa Rica</option>
              <option value="Cote D'ivoire">Cote D'ivoire</option>
              <option value="Croatia">Croatia</option>
              <option value="Cuba">Cuba</option>
              <option value="Cyprus">Cyprus</option>
              <option value="Czech Republic">Czech Republic</option>
              <option value="Denmark">Denmark</option>
              <option value="Djibouti">Djibouti</option>
              <option value="Dominica">Dominica</option>
              <option value="Dominican Republic">Dominican Republic</option>
              <option value="Ecuador">Ecuador</option>
              <option value="Egypt">Egypt</option>
              <option value="El Salvador">El Salvador</option>
              <option value="Equatorial Guinea">Equatorial Guinea</option>
              <option value="Eritrea">Eritrea</option>
              <option value="Estonia">Estonia</option>
              <option value="Ethiopia">Ethiopia</option>
              <option value="Falkland Islands (Malvinas)">Falkland Islands (Malvinas)</option>
              <option value="Faroe Islands">Faroe Islands</option>
              <option value="Fiji">Fiji</option>
              <option value="Finland">Finland</option>
              <option value="France">France</option>
              <option value="French Guiana">French Guiana</option>
              <option value="French Polynesia">French Polynesia</option>
              <option value="French Southern Territories">French Southern Territories</option>
              <option value="Gabon">Gabon</option>
              <option value="Gambia">Gambia</option>
              <option value="Georgia">Georgia</option>
              <option value="Germany">Germany</option>
              <option value="Ghana">Ghana</option>
              <option value="Gibraltar">Gibraltar</option>
              <option value="Greece">Greece</option>
              <option value="Greenland">Greenland</option>
              <option value="Grenada">Grenada</option>
              <option value="Guadeloupe">Guadeloupe</option>
              <option value="Guam">Guam</option>
              <option value="Guatemala">Guatemala</option>
              <option value="Guernsey">Guernsey</option>
              <option value="Guinea">Guinea</option>
              <option value="Guinea-bissau">Guinea-bissau</option>
              <option value="Guyana">Guyana</option>
              <option value="Haiti">Haiti</option>
              <option value="Heard Island and Mcdonald Islands">
                Heard Island and Mcdonald Islands
              </option>
              <option value="Holy See (Vatican City State)">Holy See (Vatican City State)</option>
              <option value="Honduras">Honduras</option>
              <option value="Hong Kong">Hong Kong</option>
              <option value="Hungary">Hungary</option>
              <option value="Iceland">Iceland</option>
              <option value="India">India</option>
              <option value="Indonesia">Indonesia</option>
              <option value="Iran, Islamic Republic of">Iran, Islamic Republic of</option>
              <option value="Iraq">Iraq</option>
              <option value="Ireland">Ireland</option>
              <option value="Isle of Man">Isle of Man</option>
              <option value="Israel">Israel</option>
              <option value="Italy">Italy</option>
              <option value="Jamaica">Jamaica</option>
              <option value="Japan">Japan</option>
              <option value="Jersey">Jersey</option>
              <option value="Jordan">Jordan</option>
              <option value="Kazakhstan">Kazakhstan</option>
              <option value="Kenya">Kenya</option>
              <option value="Kiribati">Kiribati</option>
              <option value="Korea, Democratic People's Republic of">
                Korea, Democratic People's Republic of
              </option>
              <option value="Korea, Republic of">Korea, Republic of</option>
              <option value="Kuwait">Kuwait</option>
              <option value="Kyrgyzstan">Kyrgyzstan</option>
              <option value="Lao People's Democratic Republic">
                Lao People's Democratic Republic
              </option>
              <option value="Latvia">Latvia</option>
              <option value="Lebanon">Lebanon</option>
              <option value="Lesotho">Lesotho</option>
              <option value="Liberia">Liberia</option>
              <option value="Libyan Arab Jamahiriya">Libyan Arab Jamahiriya</option>
              <option value="Liechtenstein">Liechtenstein</option>
              <option value="Lithuania">Lithuania</option>
              <option value="Luxembourg">Luxembourg</option>
              <option value="Macao">Macao</option>
              <option value="Macedonia, The Former Yugoslav Republic of">
                Macedonia, The Former Yugoslav Republic of
              </option>
              <option value="Madagascar">Madagascar</option>
              <option value="Malawi">Malawi</option>
              <option value="Malaysia">Malaysia</option>
              <option value="Maldives">Maldives</option>
              <option value="Mali">Mali</option>
              <option value="Malta">Malta</option>
              <option value="Marshall Islands">Marshall Islands</option>
              <option value="Martinique">Martinique</option>
              <option value="Mauritania">Mauritania</option>
              <option value="Mauritius">Mauritius</option>
              <option value="Mayotte">Mayotte</option>
              <option value="Mexico">Mexico</option>
              <option value="Micronesia, Federated States of">
                Micronesia, Federated States of
              </option>
              <option value="Moldova, Republic of">Moldova, Republic of</option>
              <option value="Monaco">Monaco</option>
              <option value="Mongolia">Mongolia</option>
              <option value="Montenegro">Montenegro</option>
              <option value="Montserrat">Montserrat</option>
              <option value="Morocco">Morocco</option>
              <option value="Mozambique">Mozambique</option>
              <option value="Myanmar">Myanmar</option>
              <option value="Namibia">Namibia</option>
              <option value="Nauru">Nauru</option>
              <option value="Nepal">Nepal</option>
              <option value="Netherlands">Netherlands</option>
              <option value="Netherlands Antilles">Netherlands Antilles</option>
              <option value="New Caledonia">New Caledonia</option>
              <option value="New Zealand">New Zealand</option>
              <option value="Nicaragua">Nicaragua</option>
              <option value="Niger">Niger</option>
              <option value="Nigeria">Nigeria</option>
              <option value="Niue">Niue</option>
              <option value="Norfolk Island">Norfolk Island</option>
              <option value="Northern Mariana Islands">Northern Mariana Islands</option>
              <option value="Norway">Norway</option>
              <option value="Oman">Oman</option>
              <option value="Pakistan">Pakistan</option>
              <option value="Palau">Palau</option>
              <option value="Palestinian Territory, Occupied">
                Palestinian Territory, Occupied
              </option>
              <option value="Panama">Panama</option>
              <option value="Papua New Guinea">Papua New Guinea</option>
              <option value="Paraguay">Paraguay</option>
              <option value="Peru">Peru</option>
              <option value="Philippines">Philippines</option>
              <option value="Pitcairn">Pitcairn</option>
              <option value="Poland">Poland</option>
              <option value="Portugal">Portugal</option>
              <option value="Puerto Rico">Puerto Rico</option>
              <option value="Qatar">Qatar</option>
              <option value="Reunion">Reunion</option>
              <option value="Romania">Romania</option>
              <option value="Russian Federation">Russian Federation</option>
              <option value="Rwanda">Rwanda</option>
              <option value="Saint Helena">Saint Helena</option>
              <option value="Saint Kitts and Nevis">Saint Kitts and Nevis</option>
              <option value="Saint Lucia">Saint Lucia</option>
              <option value="Saint Pierre and Miquelon">Saint Pierre and Miquelon</option>
              <option value="Saint Vincent and The Grenadines">
                Saint Vincent and The Grenadines
              </option>
              <option value="Samoa">Samoa</option>
              <option value="San Marino">San Marino</option>
              <option value="Sao Tome and Principe">Sao Tome and Principe</option>
              <option value="Saudi Arabia">Saudi Arabia</option>
              <option value="Senegal">Senegal</option>
              <option value="Serbia">Serbia</option>
              <option value="Seychelles">Seychelles</option>
              <option value="Sierra Leone">Sierra Leone</option>
              <option value="Singapore">Singapore</option>
              <option value="Slovakia">Slovakia</option>
              <option value="Slovenia">Slovenia</option>
              <option value="Solomon Islands">Solomon Islands</option>
              <option value="Somalia">Somalia</option>
              <option value="South Africa">South Africa</option>
              <option value="South Georgia and The South Sandwich Islands">
                South Georgia and The South Sandwich Islands
              </option>
              <option value="Spain">Spain</option>
              <option value="Sri Lanka">Sri Lanka</option>
              <option value="Sudan">Sudan</option>
              <option value="Suriname">Suriname</option>
              <option value="Svalbard and Jan Mayen">Svalbard and Jan Mayen</option>
              <option value="Swaziland">Swaziland</option>
              <option value="Sweden">Sweden</option>
              <option value="Switzerland">Switzerland</option>
              <option value="Syrian Arab Republic">Syrian Arab Republic</option>
              <option value="Taiwan">Taiwan</option>
              <option value="Tajikistan">Tajikistan</option>
              <option value="Tanzania, United Republic of">Tanzania, United Republic of</option>
              <option value="Thailand">Thailand</option>
              <option value="Timor-leste">Timor-leste</option>
              <option value="Togo">Togo</option>
              <option value="Tokelau">Tokelau</option>
              <option value="Tonga">Tonga</option>
              <option value="Trinidad and Tobago">Trinidad and Tobago</option>
              <option value="Tunisia">Tunisia</option>
              <option value="Turkey">Turkey</option>
              <option value="Turkmenistan">Turkmenistan</option>
              <option value="Turks and Caicos Islands">Turks and Caicos Islands</option>
              <option value="Tuvalu">Tuvalu</option>
              <option value="Uganda">Uganda</option>
              <option value="Ukraine">Ukraine</option>
              <option value="United Arab Emirates">United Arab Emirates</option>
              <option value="United Kingdom">United Kingdom</option>
              <option value="United States">United States</option>
              <option value="United States Minor Outlying Islands">
                United States Minor Outlying Islands
              </option>
              <option value="Uruguay">Uruguay</option>
              <option value="Uzbekistan">Uzbekistan</option>
              <option value="Vanuatu">Vanuatu</option>
              <option value="Venezuela">Venezuela</option>
              <option value="Viet Nam">Viet Nam</option>
              <option value="Virgin Islands, British">Virgin Islands, British</option>
              <option value="Virgin Islands, U.S.">Virgin Islands, U.S.</option>
              <option value="Wallis and Futuna">Wallis and Futuna</option>
              <option value="Western Sahara">Western Sahara</option>
              <option value="Yemen">Yemen</option>
              <option value="Zambia">Zambia</option>
              <option value="Zimbabwe">Zimbabwe</option>
            </select>
          </div>

          <div className="col-span-1">
            <label htmlFor="zipcodeInput" className="inline-block mb-2 text-sm text-default-800 font-medium">
              ZipCode
            </label>
            <input type="text" id="zipcodeInput" className="form-input" placeholder="ZipCode" />
          </div>
        </div>
      </div>

      <div className="p-5 card mb-5">
        <h6 className="card-title mb-4">Delivery</h6>

        <div className="grid lg:grid-cols-2 grid-cols-1 gap-5">
          <div className="flex gap-2.5 items-center">
            <input type="radio" className="peer form-radio" id="radio_1" name="level" defaultChecked value="1" />
            <label className="flex lg:flex-nowrap flex-wrap justify-between border border-default-200 w-full peer-checked:border-primary rounded-md p-5 gap-4" htmlFor="radio_1">
              <div className="flex gap-4">
                <img src={delivery01} alt="" className="h-12" width={48} />

                <span className="grow">
                  <span className="block mb-1 font-semibold text-default-800 text-[15px]">
                    Express Delivery
                  </span>
                  <span className="text-default-500 text-sm">
                    Expected delivery: 01 Nov, Wednesday
                  </span>
                </span>
              </div>

              <span className="text-lg text-default-800 font-semibold">$11.99 </span>
            </label>
          </div>

          <div className="flex items-center gap-2.5">
            <input type="radio" className="peer form-radio" id="radio_2" name="level" value="2" />
            <label className="flex flex-wrap justify-between border border-default-200 w-full peer-checked:border-primary rounded-md p-5 gap-4" htmlFor="radio_2">
              <div className="flex gap-4">
                <img src={delivery02} alt="" className="h-12" width={48} />

                <span className="grow">
                  <span className="block mb-1 font-semibold text-[15px] text-default-800">
                    Air Logistic Delivery
                  </span>
                  <span className="text-default-500 text-sm">
                    Expected delivery: 06 Nov, Monday
                  </span>
                </span>
              </div>

              <span className="text-lg text-default-800 font-semibold">$5</span>
            </label>
          </div>

          <div className="flex gap-2.5 items-center">
            <input type="radio" className="peer form-radio" id="radio_3" name="level" value="3" />
            <label className="flex flex-wrap justify-between border border-default-200 w-full peer-checked:border-primary rounded-md p-5 gap-4" htmlFor="radio_3">
              <div className="flex gap-4">
                <img src={delivery03} alt="" className="h-12" width={48} />

                <span className="grow">
                  <span className="block mb-1 font-semibold text-default-800 text-[15px]">
                    Free Delivery
                  </span>
                  <span className="text-default-500 text-sm">
                    Expected delivery: 11 Nov, Saturday
                  </span>
                </span>
              </div>

              <span className="text-lg text-default-800 font-semibold">$0 </span>
            </label>
          </div>
        </div>
      </div>

      <div className="card p-5 mb-5">
        <h6 className="card-title mb-4">Payment Information</h6>

        <div className="mb-5">
          <label htmlFor="cardNumberInput" className="inline-block mb-2 text-sm text-default-800 font-medium">
            Card Number
          </label>
          <input type="text" pattern="\d*" maxLength={16} id="cardNumberInput" className="form-input" placeholder="XXXX XXXX XXXX XXXX" />
        </div>

        <div className="grid lg:grid-cols-2 grid-cols-1 gap-5">
          <div className="col-span-1">
            <label htmlFor="expiringInput" className="inline-block mb-2 text-sm text-default-800 font-medium">
              Expiring (MM/YY)
            </label>
            <input type="text" pattern="\d*" maxLength={4} id="expiringInput" className="form-input" placeholder="MM/YY" />
          </div>

          <div className="col-span-1">
            <label htmlFor="cvvInput" className="inline-block mb-2 text-sm text-default-800 font-medium">
              CVV Code
            </label>
            <input type="text" pattern="\d*" maxLength={3} id="cvvInput" className="form-input" placeholder="000" />
          </div>
        </div>

        <div className="mt-3">
          <h6 className="inline-block mb-2 text-sm text-default-800 font-medium">
            We accept the following cards
          </h6>
          <div className="flex items-center gap-2">
            <img src={payment01} alt="" className="h-8" width={32} />
            <img src={payment02} alt="" className="h-8" width={32} />
            <img src={payment03} alt="" className="h-8" width={32} />
            <img src={payment04} alt="" className="h-8" width={32} />
          </div>
        </div>
      </div>
    </div>;
};
export default ShoppingInformation;
