// Nextjs-JS/src/app/(admin)/(app)/notes/components/Notes.jsx
import Link from 'next/link';
import React from 'react';
import { LuEllipsis, LuEye, LuSquarePen, LuStar, LuTrash2 } from 'react-icons/lu';
const notesData = [{
  id: 1,
  title: 'Show Then Our Research',
  description: 'You should identify and anticipate any ethical issues or dilemmas that may arise during or after your research, and how you will resolve them.You should identify and anticipate any ethical issues or dilemmas that may arise during...',
  date: '16 May, 2023',
  category: 'Personal',
  categoryColor: 'bg-primary/15 border-primary',
  isStarred: true
}, {
  id: 2,
  title: 'New People Hiring',
  description: 'Steps to recruiting employees',
  details: ['Consider your actual needs', 'Conduct interviews with top applicants', 'Don’t take too long to hire', 'Making the offer'],
  date: '24 Mar, 2023',
  category: 'Business',
  categoryColor: 'bg-danger/15 border-danger',
  isStarred: false
}, {
  id: 3,
  title: 'Design Tools',
  description: 'Visual design tools are, for example, gesture, sketch, drawing, scale model, perspective drawing, photograph, film, video. These include flowcharts, pseudocode, and Nassi-Shneiderman diagrams.',
  date: '29 Feb, 2023',
  category: 'Social',
  categoryColor: 'bg-secondary/10 border-secondary',
  isStarred: true
}, {
  id: 4,
  title: 'Create Chat Apps',
  description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  date: '01 Jan, 2023',
  category: 'Home',
  categoryColor: 'bg-success/10 border-success',
  isStarred: false
}, {
  id: 5,
  title: 'Show Then Our Research',
  description: 'You should identify and anticipate any ethical issues or dilemmas that may arise during or after your research, and how you will resolve them.You should identify and anticipate any ethical issues or dilemmas that may arise during...',
  date: '16 May, 2023',
  category: 'Personal',
  categoryColor: 'bg-primary/15 border-primary',
  isStarred: true
}, {
  id: 6,
  title: 'New People Hiring',
  description: 'Steps to recruiting employees',
  details: ['Consider your actual needs', 'Conduct interviews with top applicants', 'Don’t take too long to hire', 'Making the offer'],
  date: '24 Mar, 2023',
  category: 'Business',
  categoryColor: 'bg-danger/15 border-danger',
  isStarred: false
}, {
  id: 7,
  title: 'Boarding is Important Thing',
  description: 'Living away from home and residing on campus in a dorm setting provides invaluable opportunities for personal growth. Boarding school students tend to develop life Business such as time management, work ethic',
  date: '29 Mar, 2023',
  category: 'Personal',
  categoryColor: 'bg-primary/10 border-primary',
  isStarred: false
}, {
  id: 8,
  title: 'Company Improvements',
  description: "Improving a business's performance requires a strategic and holistic approach that focuses on key areas such as setting and tracking KPIs, improving operational efficiency.",
  date: '10 Apr, 2023',
  category: 'Business',
  categoryColor: 'bg-secondary/10 border-secondary',
  isStarred: true
}];
const Notes = () => {
  return <div className="grid lg:grid-cols-4 md:grid-cols-2 grid-cols-1 gap-5">
      {notesData.map(note => <div key={note.id} className="card">
          <div className="card-body">
            <div className="flex flex-col justify-between h-full">
              <div className="mb-5 flex justify-between items-center gap-2">
                <div className="flex gap-2 items-center">
                  <div className="hs-dropdown relative inline-flex">
                    <button type="button" className={`hs-dropdown-toggle size-4 border border-dashed rounded-full shrink-0 ${note.categoryColor}`} aria-haspopup="menu" aria-expanded="false" />
                    <div className="hs-dropdown-menu" role="menu">
                      {['Personal', 'Business', 'Social', 'Home'].map(cat => <Link key={cat} href="#" className="flex items-center gap-x-3.5 py-1.5 font-medium px-3 text-sm text-default-600 hover:bg-default-150 rounded">
                          {cat}
                        </Link>)}
                    </div>
                  </div>
                  <h5 className="card-title">{note.title}</h5>
                </div>
                <div className="hs-dropdown relative inline-flex">
                  <button type="button" className="hs-dropdown-toggle btn size-7.5 bg-default-200 hover:bg-default-600 text-default-500 hover:text-white">
                    <LuEllipsis className="size-4" />
                  </button>
                  <div className="hs-dropdown-menu" role="menu">
                    <Link href="#" className="flex items-center gap-1.5 py-1.5 font-medium px-3 text-default-500 hover:bg-default-150 rounded">
                      <LuEye className="size-3" /> Overview
                    </Link>
                    <Link href="#" className="flex items-center gap-1.5 py-1.5 font-medium px-3 text-default-500 hover:bg-default-150 rounded">
                      <LuSquarePen className="size-3" /> Edit
                    </Link>
                    <Link href="#" className="flex items-center gap-1.5 py-1.5 font-medium px-3 text-default-500 hover:bg-default-150 rounded">
                      <LuTrash2 className="size-3" /> Delete
                    </Link>
                  </div>
                </div>
              </div>

              {note.details ? <div>
                  <p className="text-default-800 font-semibold text-sm">{note.description}</p>
                  <ol className="flex flex-col text-default-600 gap-1 text-sm mt-1">
                    {note.details.map((d, i) => <li key={i}>{d}</li>)}
                  </ol>
                </div> : <p className="text-default-700 text-sm">{note.description}</p>}

              <div className="mt-4 flex justify-between gap-3 items-center">
                <LuStar className={`${note.isStarred ? 'text-warning fill-warning/20' : 'text-default-500 fill-default-200'} size-5`} />
                <p className="text-default-500 text-sm">{note.date}</p>
              </div>
            </div>
          </div>
        </div>)}
    </div>;
};
export default Notes;

// Nuxtjs/app/pages/apps/notes/components/Notes.vue
<template>
  <div class="grid lg:grid-cols-4 md:grid-cols-2 grid-cols-1 gap-5">
    <div class="card" v-for="(item, idx) in cards" :key="idx">
      <div class="card-body">
        <div class="flex flex-col justify-between h-full">
          <div class="mb-5 flex justify-between items-center gap-2">
            <div class="flex gap-2 items-center">
              <div class="hs-dropdown relative inline-flex">
                <button type="button" :class="item.buttonBg" class="hs-dropdown-toggle size-4 border border-dashed rounded-full dropdown-toggle shrink-0" aria-haspopup="menu" aria-expanded="false" aria-label="Dropdown"></button>
                <div class="hs-dropdown-menu" role="menu">
                  <div>
                    <a class="flex items-center gap-x-3.5 py-1.5 font-medium px-3 text-sm text-default-600 hover:bg-default-150 rounded" href=""> Personal </a>
                    <a class="flex items-center gap-x-3.5 py-1.5 font-medium px-3 text-sm text-default-600 hover:bg-default-150 rounded" href=""> Busssiness </a>
                    <a class="flex items-center gap-x-3.5 py-1.5 font-medium px-3 text-sm text-default-600 hover:bg-default-150 rounded" href=""> Social </a>
                    <a class="flex items-center gap-x-3.5 py-1.5 font-medium px-3 text-sm text-default-600 hover:bg-default-150 rounded" href=""> Home </a>
                  </div>
                </div>
              </div>
              <h5 class="card-title">{{ item.title }}</h5>
            </div>
            <div class="hs-dropdown [--placement:bottom-right] relative inline-flex">
              <button type="button" class="hs-dropdown-toggle btn size-7.5 bg-default-200 hover:bg-default-600 text-default-500 hover:text-white" aria-haspopup="menu" aria-expanded="false" aria-label="Dropdown" hs-dropdown-placement="bottom-end">
                <Icon icon="lucide:ellipsis" class="iconify size-4"></Icon>
              </button>
              <div class="hs-dropdown-menu" role="menu">
                <a class="flex items-center gap-1.5 py-1.5 font-medium px-3 text-default-500 hover:bg-default-150 rounded" href="">
                  <Icon icon="lucide:eye" class="size-3"></Icon>
                  Overview
                </a>
                <a class="flex items-center gap-1.5 py-1.5 font-medium px-3 text-default-500 hover:bg-default-150 rounded" href="">
                  <Icon icon="lucide:edit" class="size-3"></Icon>
                  Edit
                </a>
                <a class="flex items-center gap-1.5 py-1.5 font-medium px-3 text-default-500 hover:bg-default-150 rounded" href="">
                  <Icon icon="lucide:trash-2" class="size-3"></Icon>
                  Delete
                </a>
              </div>
            </div>
          </div>
          <p class="text-default-700 text-sm" v-html="item.description"></p>
          <div v-if="item.date" class="mt-4 flex justify-between gap-3 items-center">
            <Icon icon="lucide:star" :class="item.class" class="size-5"></Icon>
            <p class="text-default-500 text-sm">{{ item.date }}</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { Icon } from '@iconify/vue'

type CardType = {
  buttonBg: string
  title: string
  description: string
  date?: string
  class: string
}

const cards: CardType[] = [
  {
    buttonBg: 'bg-primary/15 border-primary',
    title: 'Show Then Our Research',
    description: 'You should identify and anticipate any ethical issues or dilemmas that may arise during or after your research, and how you will resolve them.You should identify and anticipate any ethical issues or dilemmas that may arise during...',
    date: '16 May, 2023',
    class: 'text-warning fill-warning/20'
  },
  {
    buttonBg: 'bg-danger/15 border-danger',
    title: 'New People Hiring',
    description: `Steps to recruiting employees
      <ol class="flex flex-col text-default-600 gap-1 text-sm mt-1">
        <li>Consider your actual needs</li>
        <li>Conduct interviews with top applicants</li>
        <li>Don’t take too long to hire</li>
        <li>Making the offer</li>
      </ol>`,
    date: '24 Mar,2023',
    class: 'text-default-500 fill-default-200'
  },
  {
    buttonBg: 'bg-secondary/10 border-secondary',
    title: 'Design Tools',
    description: 'Visual design tools are, for example, gesture, sketch, drawing, scale model, perspective drawing, photograph, film, video. These include flowcharts, pseudocode, and Nassi-Shneiderman diagrams.',
    date: '29 Feb, 2023',
    class: 'text-warning fill-warning/20'
  },
  {
    buttonBg: 'bg-success/10 border-success',
    title: 'Create Chat Apps',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    class: 'text-default-500 fill-default-200',
    date: '01 Jan, 2023'
  },
  {
    buttonBg: 'bg-primary/15 border-primary',
    title: 'Show Then Our Research',
    description: 'You should identify and anticipate any ethical issues or dilemmas that may arise during or after your research, and how you will resolve them. You should also consider the impact and consequences of your research on different stakeholders.',
    class: 'text-warning fill-warning/20',
    date: '16 May, 2023'
  },
  {
    buttonBg: 'bg-danger/15 border-danger',
    title: 'New People Hiring',
    description: `Steps to recruiting employees
      <ol class="flex flex-col text-default-600 gap-1 text-sm mt-1">
        <li>Consider your actual needs</li>
        <li>Conduct interviews with top applicants</li>
        <li>Don’t take too long to hire</li>
        <li>Making the offer</li>
      </ol>`,
    class: 'text-default-500 fill-default-200',
    date: '24 Mar, 2023'
  },
  {
    buttonBg: 'bg-primary/10 border-primary',
    title: 'Boarding is Important Thing',
    description: 'Living away from home and residing on campus in a dorm setting provides invaluable opportunities for personal growth. Boarding school students tend to develop life Business such as time management, work ethic',
    class: 'text-default-500 fill-default-200',
    date: '29 Mar, 2023'
  },
  {
    buttonBg: 'bg-secondary/10 border-secondary',
    title: 'Company Improvements',
    description: "Improving a business's performance requires a strategic and holistic approach that focuses on key areas such as setting and tracking KPIs, improving operational efficiency.",
    date: '09 Jun, 2023',
    class: 'text-warning fill-warning/20'
  }
]
</script>
