// Nextjs-JS/src/app/(admin)/(dashboards)/email/page.jsx
import PageBreadcrumb from '@/components/PageBreadcrumb';
import React from 'react';
import EmailLineChart from './components/EmailLineChart';
import EmailBarChart from './components/EmailBarChart';
import EmailData from './components/EmailData';
import EmailMarketing from './components/EmailMarketing';
import ComposeEmail from './components/ComposeEmail';
import EmailPerformance from './components/EmailPerformance';
export const metadata = {
  title: 'Email'
};
const Page = () => {
  return <main>
      <PageBreadcrumb title="Email Analytics" subtitle="Dashboard" />
      <EmailLineChart />
      <EmailBarChart />
      <div className="grid lg:grid-cols-4 grid-cols-1 gap-5 mb-5">
        <EmailData />
        <EmailMarketing />
        <ComposeEmail />
      </div>
      <EmailPerformance />
    </main>;
};
export default Page;

// Nuxtjs/app/pages/dashboard/email/index.vue
<template>
  <Vertical>
    <PageTitle title="Email Analytics" subtitle="Dashboards" />

    <EmailAnalyticsStats />
    <EmailHealthStats />
    <div class="grid lg:grid-cols-4 grid-cols-1 gap-5 mb-5">
      <EmailData />
      <EmailMarketing />
      <Experience />
    </div>

    <EmailPerformance />
  </Vertical>
</template>

<script setup lang="ts">
import PageTitle from '~/components/PageTitle.vue'
import Vertical from '~/layouts/vertical.vue'
import EmailAnalyticsStats from './components/EmailAnalyticsStats.vue'
import EmailHealthStats from './components/EmailHealthStats.vue'
import EmailData from './components/EmailData.vue'
import EmailMarketing from './components/EmailMarketing.vue'
import Experience from './components/Experience.vue'
import EmailPerformance from './components/EmailPerformance.vue'

usePageTitle('Email Analytics')
</script>
