// Vuejs/src/views/(pages)/pricing/index.vue
<template>
  <Vertical>
    <PageTitle subtitle="Pages" title="Pricing" />
    <Pricing />
    <h5 class="mt-2 mb-4 underline text-lg font-semibold text-default-700">Horizontal Pricing</h5>
    <HorizontalPricing />
  </Vertical>
</template>

<script setup lang="ts">
import PageTitle from '@/components/PageTitle.vue'
import Vertical from '@/layouts/vertical.vue'
import HorizontalPricing from './components/HorizontalPricing.vue'
import Pricing from './components/Pricing.vue'
</script>

// React-JS/src/app/(admin)/(pages)/pricing/index.jsx
import PageBreadcrumb from '@/components/PageBreadcrumb';
import PageMeta from '@/components/PageMeta';
import HorizontalPricing from './components/HorizontalPricing';
import Pricing from './components/PricingCard';
const Index = () => {
  return <>
      <PageMeta title="Pricing" />
      <main>
        <PageBreadcrumb title="Pricing" subtitle="Pages" />
        <Pricing />
        <HorizontalPricing />
      </main>
    </>;
};
export default Index;
