// Nextjs-JS/src/app/(admin)/(app)/calendar/page.jsx
import PageBreadcrumb from '@/components/PageBreadcrumb';
import Calender from './components/Calender';
export const metadata = {
  title: 'Calendar'
};
const Page = () => {
  return <main>
      <PageBreadcrumb title="Calendar" subtitle="Menu" />
      <div className="grid lg:grid-cols-4 gap-5">
        <Calender />
      </div>
    </main>;
};
export default Page;

// Vuejs/src/views/apps/calendar/index.vue
<template>
  <Vertical>
    <PageTitle subtitle="Menu" title="Calendar" />
    <div class="grid lg:grid-cols-4 gap-5">
      <Calendar />
      <Event />
    </div>
  </Vertical>
</template>

<script setup lang="ts">
import PageTitle from '@/components/PageTitle.vue'
import Vertical from '@/layouts/vertical.vue'
import Calendar from './components/Calendar.vue'
import Event from './components/Event.vue'
</script>
