// React-JS/src/app/(admin)/(app)/(invoice)/list/index.jsx
import PageBreadcrumb from '@/components/PageBreadcrumb';
import InvoiceList from './components/InvoiceList';
import InvoiceDetails from './components/InvoiceDetails';
import PageMeta from '@/components/PageMeta';
const Index = () => {
  return <>
      <PageMeta title="Invoice List" />
      <main>
        <PageBreadcrumb title="List View" subtitle="Menu" />
        <div className="grid lg:grid-cols-4 grid-cols-1 gap-5">
          <InvoiceList />
          <InvoiceDetails />
        </div>
      </main>
    </>;
};
export default Index;

// Vuejs/src/views/invoice/list/index.vue
<template>
  <Vertical>
    <PageTitle subtitle="Menu" title="List View" />

    <div class="grid lg:grid-cols-4 grid-cols-1 gap-5">
      <InvoiceList />
      <InvoiceForm />
    </div>
  </Vertical>
</template>

<script setup lang="ts">
import PageTitle from '@/components/PageTitle.vue'
import Vertical from '@/layouts/vertical.vue'
import InvoiceList from './components/InvoiceList.vue'
import InvoiceForm from './components/InvoiceForm.vue'

</script>
