// Nuxtjs/app/pages/dashboard/analytics/components/AnalyticsReports.vue
<template>
  <div class="card">
    <div class="card-header mb-4">
      <h6 class="card-title">Analytics Reports</h6>
    </div>
    <div class="card-body">
      <client-only>
        <VueApexCharts type="line" height="260" :options="analyticschartOptions" :series="analyticsseries" />
      </client-only>
    </div>
  </div>
</template>

<script setup lang="ts">
import VueApexCharts from 'vue3-apexcharts'
import { analyticschartOptions, analyticsseries } from './data'
</script>

// React-JS/src/app/(admin)/(dashboards)/analytics/components/AnalyticsReports.jsx
import ApexChartClient from '@/components/client-wrapper/ApexChartClient';
import { getAnalyticsReports } from './data';
const AnalyticsReports = () => {
  return <div className="card">
      <div className="card-header mb-4">
        <h6 className="card-title">Analytics Reports</h6>
      </div>

      <div className="card-body">
        <ApexChartClient getOptions={getAnalyticsReports} series={getAnalyticsReports().series} type="line" height={260} />
      </div>
    </div>;
};
export default AnalyticsReports;
