// Vuejs/src/views/hr-management/(leave-manage)/leave-employee/index.vue
<template>
  <Vertical>
    <PageTitle subtitle="Menu" title="Leave Manage (Employee)" />
    <div class="grid lg:grid-cols-4 md:grid-cols-2 grid-cols-1 gap-5 mb-5">
      <StatCard />
    </div>
    <Table />
  </Vertical>
</template>

<script setup lang="ts">
import PageTitle from '@/components/PageTitle.vue'
import Vertical from '@/layouts/vertical.vue'
import StatCard from './components/StatCard.vue'
import Table from './components/Table.vue'

</script>

// apps/web/src/app/(admin)/(app)/(hr)/leave-employee/index.tsx
import PageBreadcrumb from '@/components/PageBreadcrumb';
import PageMeta from '@/components/PageMeta';
import EmpLeave from './components/EmpLeave';
import LeaveCard from './components/LeaveCard';

const Index = () => {
  return (
    <>
      <PageMeta title="Leave Manage (Employee)" />
      <main>
        <PageBreadcrumb title="Leave Manage (Employee)" subtitle="Menu" />
        <LeaveCard />
        <EmpLeave />
      </main>
    </>
  );
};

export default Index;
