// Nuxtjs/app/pages/invoice/list/index.vue
<template>
  <Vertical>
    <PageTitle subtitle="Menu" title="List View" />

    <div class="grid lg:grid-cols-4 grid-cols-1 gap-5">
      <InvoiceList />
      <InvoiceForm />
    </div>
  </Vertical>
</template>

<script setup lang="ts">
import PageTitle from '~/components/PageTitle.vue'
import Vertical from '~/layouts/vertical.vue'
import InvoiceList from './components/InvoiceList.vue'
import InvoiceForm from './components/InvoiceForm.vue'

usePageTitle('List View')
</script>

// Nextjs-JS/src/app/(admin)/(app)/(invoice)/list/page.jsx
import PageBreadcrumb from '@/components/PageBreadcrumb';
import React from 'react';
import InvoiceList from './components/InvoiceList';
import InvoiceDetails from './components/InvoiceDetails';
export const metadata = {
  title: 'Invoice List'
};
const Page = () => {
  return <main>
      <PageBreadcrumb title="List View" subtitle="Menu" />
      <div className="grid lg:grid-cols-4 grid-cols-1 gap-5">
        <InvoiceList />
        <InvoiceDetails />
      </div>
    </main>;
};
export default Page;
