// Nuxtjs/app/pages/apps/notes/index.vue
<template>
  <Vertical>
    <PageTitle title="Notes" subtitle="Menu" />
    <Note />
  </Vertical>
</template>

<script setup lang="ts">
import PageTitle from '~/components/PageTitle.vue'
import Vertical from '~/layouts/vertical.vue'
import Note from './components/Notes.vue'

usePageTitle('Notes')
</script>

// Nextjs-JS/src/app/(admin)/(app)/notes/page.jsx
import PageBreadcrumb from '@/components/PageBreadcrumb';
import React from 'react';
import Notes from './components/Notes';
export const metadata = {
  title: 'Notes'
};
const Page = () => {
  return <main>
      <PageBreadcrumb title="Notes" subtitle="Menu" />
      <Notes />
    </main>;
};
export default Page;
