// Vuejs/src/views/hr-management/(attendance)/attendance-main/index.vue
<template>
  <Vertical>
    <PageTitle subtitle="Menu" title="Main Attendance" />
    <Stat />
    <Table />
  </Vertical>
</template>

<script setup lang="ts">
import PageTitle from '@/components/PageTitle.vue'
import Vertical from '@/layouts/vertical.vue'
import Stat from './components/Stat.vue'
import Table from './components/Table.vue'

</script>

// React-TS/src/app/(admin)/(app)/(hr)/attendance-main/index.tsx
import PageBreadcrumb from '@/components/PageBreadcrumb';
import PageMeta from '@/components/PageMeta';
import EmployeeReport from './components/EmployeeReport';
import EmployeeReportTabel from './components/EmployeeReportTabel';

const Index = () => {
  return (
    <>
      <PageMeta title="Main Attendance" />
      <main>
        <PageBreadcrumb title="Main Attendance" subtitle="Menu" />
        <EmployeeReport />
        <EmployeeReportTabel />
      </main>
    </>
  );
};

export default Index;
