// Vuejs/src/views/ecommerce/product-grid/index.vue
<template>
  <Vertical>
    <PageTitle subtitle="Menu" title="Grid View" />
    <div class="grid lg:grid-cols-4 grid-cols-1 gap-5">
      <Filter />
      <Product />
    </div>
  </Vertical>
</template>

<script setup lang="ts">
import PageTitle from '@/components/PageTitle.vue'
import Vertical from '@/layouts/vertical.vue'
import Filter from './components/Filter.vue'
import Product from './components/Product.vue'
</script>

// React-JS/src/app/(admin)/(app)/(ecommerce)/product-grid/index.jsx
import PageMeta from '@/components/PageMeta';
import ProductFilter from './components/ProductFilter';
import Products from './components/Products';
import PageBreadcrumb from '@/components/PageBreadcrumb';
const Index = () => {
  return <>
      <PageMeta title="Product Grid" />
      <main>
        <PageBreadcrumb title="Product Grid" subtitle="Menu" />
        <div className="grid lg:grid-cols-4 grid-cols-1 gap-5">
          <div className="col-span-1 lg:block hidden">
            <ProductFilter />
          </div>
          <Products />
        </div>
      </main>
    </>;
};
export default Index;
