// Nuxtjs/app/pages/landing/product/index.vue
<template>
  <Header />
  <Hero />
  <Product />
  <Feature />
  <About />
  <Feedback />
  <CTA />
  <Footer />
</template>

<script setup lang="ts">
import About from './components/About.vue'
import CTA from './components/CTA.vue'
import Feature from './components/Feature.vue'
import Feedback from './components/Feedback.vue'
import Footer from './components/Footer.vue'
import Header from './components/Header.vue'
import Hero from './components/Hero.vue'
import Product from './components/Product.vue'

usePageTitle('Product')

useHead({
  bodyAttrs: {
    class: 'bg-card'
  }
})
</script>

// Angular/src/app/views/landing/product/product.ts
import { Component } from '@angular/core';
import { Header } from "./components/header/header";
import { Hero } from "./components/hero/hero";
import { Features } from "./components/features/features";
import { About } from "./components/about/about";
import { Feedback } from "./components/feedback/feedback";
import { Cta } from "./components/cta/cta";
import { Footer } from "./components/footer/footer";
import { Product1 } from "./components/product1/product1";

@Component({
  selector: 'app-product',
  imports: [Header, Hero, Product1, Features, About, Feedback, Cta, Footer],
  templateUrl: './product.html',
  styles: ``
})
export class Product {

}
