// Nuxtjs/app/pages/apps/notes/index.vue
<template>
  <Vertical>
    <PageTitle title="Notes" subtitle="Menu" />
    <Note />
  </Vertical>
</template>

<script setup lang="ts">
import PageTitle from '~/components/PageTitle.vue'
import Vertical from '~/layouts/vertical.vue'
import Note from './components/Notes.vue'

usePageTitle('Notes')
</script>

// React-TS/src/app/(admin)/(app)/notes/index.tsx
import PageBreadcrumb from '@/components/PageBreadcrumb';
import Notes from './components/Notes';
import PageMeta from '@/components/PageMeta';

const Index = () => {
  return (
    <>
      <PageMeta title="Notes" />
      <main>
        <PageBreadcrumb title="Notes" subtitle="Menu" />
        <Notes />
      </main>
    </>
  );
};

export default Index;
